### ISSUE TITLE
auth/logout throw 405 method not allowed

### ISSUE THREAD

**Issue by junhua** [sunscrapers/djoser#102]
I'm trying to follow the documentation and implement token auth. When I request auth/logout it throws a 405 "method not allowed" error. Any idea?

@haxoza

**Comment by haxoza** [comment]
Hi! I guess you use GET http method so please try to send POST method.

You can see [in the code that only POST is available](https://github.com/sunscrapers/djoser/blob/master/djoser/views.py#L88). This is just for security reason.

**Comment by junhua** [comment]
Cool! Just tried doing a POST request and it worked. Thanks!
