### ISSUE TITLE
Support for 1.9 `AUTH_PASSWORD_VALIDATORS`

### ISSUE THREAD

**Issue by jamiecounsell** [sunscrapers/djoser#106]
Hey! I'm trying to configure Django's new `AUTH_PASSWORD_VALIDATORS`. I'm using djoser with a custom user model, and the passwords are not being validated. The documentation for this is quite slim, so I'm wondering if extra implementation is required on the custom user model or inside djoser. Any ideas? Happy to submit a pull request, but open to recommendations and wondering if you had already considered this.

**Comment by jamiecounsell** [comment]
Opened PR #107

**Comment by mmarksnippety** [comment]
This feature is introduced in djoser 0.4.2
