### ISSUE TITLE
/login/ and /logout/ not found

### ISSUE THREAD

**Issue by lectricas** [sunscrapers/djoser#109]
How to solve this issue? I've searhed for an answer but haven't found a thing.

**Comment by lectricas** [comment]
This endpoint is available only if you are using token based authentication.?

**Comment by lectricas** [comment]
This endpoint is available only if you are using token based authentication.
what steps I should do in order to make it work?

**Comment by lectricas** [comment]
please close because I dumb.
Following the turorial at https://github.com/sunscrapers/djoser do the trick!

**Comment by lwm** [comment]
@lectricas - you can also close this issue yourself ? no ? :+1:

**Comment by lectricas** [comment]
how can I do that?

**Comment by lwm** [comment]
Well, you can see a `Close Issue` or `Close and comment` or something like that below your text input area ?

**Comment by lwm** [comment]
:+1:

**Comment by lectricas** [comment]
Thanks. Just haven't seen this btn
