### ISSUE TITLE
Updating djoser to a new version updates its dependencies

### ISSUE THREAD

**Issue by haxoza** [sunscrapers/djoser#110]
For example updating djoser to latest version when using django 1.7 updates django as well to latest version. It's because of `install_requires` in `setup.py` which is set to value of `requirements.txt` file. `install_requires` should be empty like e.g. in Django Rest Framework itself.

I believe that fix of this issue should update readme file too.

@bartekbrak thanks for your findings!

**Comment by lwm** [comment]
Possibly worth looking into [pip-tools](https://github.com/nvie/pip-tools) for dependency management.

**Comment by mmarksnippety** [comment]
@bartekbrak will do some more investigation about requirements
