### ISSUE TITLE
Authentication Token Usage

### ISSUE THREAD

**Issue by Suleiman19** [sunscrapers/djoser#112]
Hello Team,

I've tried following the sample usage which is given in your readme.txt after all the installation procedures..
The problem that I have is that once I get the authentication token after login, am not able to use the token to perform various tasks provided like able to view the details through "127.0.0.1:8000/auth/me/"
I've tried using the Authentication Token following various methods(using Postman), and via curl like u've mentioned but once I give the command..
$ curl -X GET http://127.0.0.1:8000/auth/me/ -H 'Authorization: Token 60226591e20790a7f32591dda283f984cec54cef'
I still get {"detail" : "Authentication details were not provided"} curl: (6) could not resolve host: Token 
curl : (6) could not resolve host: 60226591e20790a7f32591dda283f984cec54cef

Please help me out with this issue.
Thanks.

**Comment by EliasS87** [comment]
Hey there... I figured it out with the help of this post. [http://stackoverflow.com/questions/26814137/token-key-authentication-in-postman](url).

Set the url: http://127.0.0.1:8000/auth/me/
Change Http request type to GET
Go under Headers, add a header with a key of Authorization, and value of:  Token (your token).
Hit Send and there you go! You should get the user data back finally.

**Comment by Yawan-1** [comment]
Hello @haxoza , I am also trying to send `Get` with Postman to get the current user according to your instructions But this is not working for me, It is still showing **401 Unauthorized**.

I have set the `url` to 
````
http://127.0.0.1:8000/api/v1/users/me/
````
and set the token key as `Authorization` with user token taken from `django admin`.
