### ISSUE TITLE
djoser should return 204 instead of 200

### ISSUE THREAD

**Issue by lwm** [sunscrapers/djoser#118]
In the following views:

  * `LogoutView`, 
  * `PasswordResetView`, 
  * `SetPasswordView`, 
  * `PasswordResetConfirmView`, 
  * `ActivationView`
  * `SetUsernameView`

`djoser` returns a `HTTP_200_OK` 

```
return response.Response(status=status.HTTP_200_OK)
```

but there is no content, so it should be a `HTTP_204_NO_CONTENT`:

```
return response.Response(status=status.HTTP_204_NO_CONTENT)
```

**Comment by haxoza** [comment]
[Merged](https://github.com/sunscrapers/djoser/commit/2ad9f1cffa71a4c67b4a3d82515fe7502bc6a413)! 🎉
