### ISSUE TITLE
Activation token invalidated by user login

### ISSUE THREAD

**Issue by joshgeller** [sunscrapers/djoser#120]
Hello, thanks for the great work on this library!

`ActivationView` uses Django's `PasswordResetTokenGenerator` to generate the activation token. To create this token, this class hashes internal user state, including the user's last login time. This means if the user logs in before clicking the activation link (in situations where the activation link is sent, but the user is not required to click it before logging in), the token is invalidated and will not work. The API returns a 400 with  `INVALID_TOKEN_ERROR`. 

This token hashing behavior makes sense for password reset tokens, however when creating activation tokens we should not hash the user's last login. This will allow djoser to support optional activation/confirmation links.

What are your thoughts on this? Would you be willing to accept a pull request?

**Comment by lwm** [comment]
> This token hashing behavior makes sense for password reset tokens

In fact, it is *only* for password resets - Django's [token generator code][1] states this.  

So, my two cents is - I think your use case is valid and something needs to be done about it.

[1]: https://github.com/django/django/blob/72e5778b23be7afec60658ebc48bb487e154fd37/django/contrib/auth/tokens.py#L18

**Comment by mmarksnippety** [comment]
Yes it is a bug. 
Fortunately in djoser 0.4.3 was merged pull request #126. So now this scenario is impossible. 
Registered user are inactive now and can't loging. So last_login will be not changing.

**Comment by lwm** [comment]
> So now this scenario is impossible. 

Right, correct!

So in order to get `djoser` to cover this, you could:

1) Make user registration activity configurable but keep the existing as a default (`is_active=False`).

2) Make the token generator configurable. If the developer needs to delay activation, then a new token generator needs to be used. However, I suppose this is something `djoser` could take care of ...

3) Document this use case in the README. Something like - it is possible to have a delayed user activation flow, but you need a token generator + configurable activity settings, etc.

Thoughts?

In any case, I think I will need this functionality at some point also, so would be nice to know if this is something you would consider @mmarksnippety

**Comment by bonzomontreus** [comment]
Hello! 

I would like to know if Djoser still does not cover this scenario in it's latest version and if there is a way to do it since I have not been able to find a way to make it work.

 Thanks in advance

**Comment by dekoza** [comment]
@bonzomontreus please write the exact scenario you are trying to implement. Right now `djoser` by default sets the new user accounts to inactive until activation link i clicked.

Or do you mean that password reset token is invalidated by user login?

**Comment by bonzomontreus** [comment]
What I am trying to accomplish is to let the user login without having to activate the account (automatically set `is_active=True` when an user is created) and make the "activation email" set another user field (`email_checked`) to `True`.
The problem is that the token created for the activation email becomes invalid when the user logs in due to the problem described in the [beginning of the issue](https://github.com/sunscrapers/djoser/issues/120#issue-135127228).

**Comment by lwm** [comment]
https://github.com/vooydzig/djoser/commit/78d6ee9cbdcfa29c9f2f59aa04aad1dc70e9526a seemed to do the trick but lived on a fork.

**Comment by bonzomontreus** [comment]
That's what i mean, I find it odd that the ~~bug hasnt been fixed~~ feature has not been added by now, taking into account that the fork is from 2016.
I don't mean to sound harsh, I do find the library really handy and well developed. But I think it should have this feature.

**Comment by bonzomontreus** [comment]
Workaround for this issue:

This basically generates the token for the url and then also stores it in a Users field and then it just checks if the link token maches the user token.
Plus changing the `CreateSerializer` and `ActivationSerializer` to set the user as active and then changing a different field to `True` when actually activating the user by the email.

Settings:
```
 'SERIALIZERS': {
        'user_create': 'APP.serializers.CustomUserCreateSerializer',
        'activation': 'APP.serializers.CustomActivationSerializer',
    },

'EMAIL': {
        'activation': 'APP.email.CustomActivationEmail',
    }
``` 

The code to this is [here](https://gist.github.com/bonzomontreus/1f457ed5edab2d15b0efd6f5e1439dab)

**Comment by rshrc** [comment]
> Workaround for this issue:
> 
> This basically generates the token for the url and then also stores it in a Users field and then it just checks if the link token maches the user token.
> Plus changing the `CreateSerializer` and `ActivationSerializer` to set the user as active and then changing a different field to `True` when actually activating the user by the email.
> 
> Settings:
> 
> ```
>  'SERIALIZERS': {
>         'user_create': 'APP.serializers.CustomUserCreateSerializer',
>         'activation': 'APP.serializers.CustomActivationSerializer',
>     },
> 
> 'EMAIL': {
>         'activation': 'APP.email.CustomActivationEmail',
>     }
> ```
> 
> The code to this is [here](https://gist.github.com/bonzomontreus/1f457ed5edab2d15b0efd6f5e1439dab)

So we use 'APP'? or is that the user app name that is supposed to be there or just 'APP'?

**Comment by rshrc** [comment]
> > Workaround for this issue:
> > This basically generates the token for the url and then also stores it in a Users field and then it just checks if the link token maches the user token.
> > Plus changing the `CreateSerializer` and `ActivationSerializer` to set the user as active and then changing a different field to `True` when actually activating the user by the email.
> > Settings:
> > ```
> >  'SERIALIZERS': {
> >         'user_create': 'APP.serializers.CustomUserCreateSerializer',
> >         'activation': 'APP.serializers.CustomActivationSerializer',
> >     },
> > 
> > 'EMAIL': {
> >         'activation': 'APP.email.CustomActivationEmail',
> >     }
> > ```
> > 
> > 
> > The code to this is [here](https://gist.github.com/bonzomontreus/1f457ed5edab2d15b0efd6f5e1439dab)
> 
> So we use 'APP'? or is that the user app name that is supposed to be there or just 'APP'?

resolved it.

**Comment by darshkpatel** [comment]
> Workaround for this issue:
> 
> This basically generates the token for the url and then also stores it in a Users field and then it just checks if the link token maches the user token.
> Plus changing the `CreateSerializer` and `ActivationSerializer` to set the user as active and then changing a different field to `True` when actually activating the user by the email.
> 
> Settings:
> 
> ```
>  'SERIALIZERS': {
>         'user_create': 'APP.serializers.CustomUserCreateSerializer',
>         'activation': 'APP.serializers.CustomActivationSerializer',
>     },
> 
> 'EMAIL': {
>         'activation': 'APP.email.CustomActivationEmail',
>     }
> ```
> 
> The code to this is [here](https://gist.github.com/bonzomontreus/1f457ed5edab2d15b0efd6f5e1439dab)

This gist for the code does not exist anymore

**Comment by mauroeparis** [comment]
Sorry, I changed my username. [Here you go!](https://gist.github.com/mauroeparis/1f457ed5edab2d15b0efd6f5e1439dab)
