### ISSUE TITLE
unhelpful error when incorrect UID is provided in password reset confirm (django 1.9)

### ISSUE THREAD

**Issue by chozabu** [sunscrapers/djoser#122]
"DjangoUnicodeDecodeError in password reset confirm" Where it probably should say something like "invalid UID"

**Comment by mmarksnippety** [comment]
Hello. 
Good point! I create new pull request: https://github.com/sunscrapers/djoser/pull/127 that resolve this issue. We will merge this changes soon

**Comment by chozabu** [comment]
Looks good!

**Comment by mmarksnippety** [comment]
Pull request #127 has been merged.
