### ISSUE TITLE
Not compatible with Django REST Framework 3.0

### ISSUE THREAD

**Issue by Zeioth** [sunscrapers/djoser#13]
post_save method doesn't exist anymore. Also, 'required' attribute is deprecated.

All changes in version 3:
http://www.django-rest-framework.org/topics/3.0-announcement/

**Comment by konradhalas** [comment]
@Zeioth it's probably fixed here https://github.com/sunscrapers/djoser/commit/1cb63683572139e52d4819417852eb3c730cbf75

We are using following approach:

```
class View(generics.CreateAPIView):

    def post_save(self, obj, created=False):
        (...)

    def perform_create(self, serializer):
        instance = serializer.save()
        self.post_save(obj=instance, created=True)
```

It's not the best, but it works.
