### ISSUE TITLE
Why is JWT support not included in this project?

### ISSUE THREAD

**Issue by shubh3794** [sunscrapers/djoser#130]
Hello!
I really liked this package as it is really complete but I am curious as I have been using JWT based OAuth in my project and I searched a lot to implement the forgot/reset password functionality, but no luck. I read djoser's source code and I am thinking I can tweak it a bit for my purpose. 
Are you going to support JWT based flows in future?

**Comment by mcgeeco** [comment]
Already under discussion: https://github.com/sunscrapers/djoser/issues/40.

For what it's worth, it's not too complex to override a few methods and sub in some rest-framework-jwt stuff.

**Comment by lwm** [comment]
@shubh3794 - it already works, just not officially. Check #105 for a working example and, yes,  #40 also has some leads :+1:

**Comment by shubh3794** [comment]
Great! Will look into it. :+1:
