### ISSUE TITLE
Ability to specify which routes to include?

### ISSUE THREAD

**Issue by oowowaee** [sunscrapers/djoser#132]
In my project I do not want users to be able to change their usernames.  I was wondering if there is another way to do this - I implemented it myself in the meantime.  I'm wondering if this warrants its own pr, and if it would be useful to extend this to other routes as well?

**Comment by lwm** [comment]
> I was wondering if there is another way to do this

You never said the way you did it first?

> I'm wondering if this warrants its own pr

This sounds more like a project specific thing. Which, is well covered by the [Customization][1] section.

> if it would be useful to extend this to other routes as well?

Not all routes handle user management?

[1]: https://github.com/sunscrapers/djoser#customization

**Comment by oowowaee** [comment]
I am wondering if there is *any* existing way to do this - the way I did it was by introducing another settings flag that is checked before adding Set username
route.

**Comment by piotr-szpetkowski** [comment]
Hi.
Easiest solution to solve the problem would be to copy patterns that are useful for your case to your app urlpatterns. You can also override the `set_username` serializer with a dummy, which on validate will always return `ValidationError` saying that the user is not allowed to use it.

Introducing a setting to turn on/off each view would essentially turn djoser into setting creep, which is definitely not what we are after. I'm going to close this issue, however in case of further problems you are welcome to open a new one.
