### ISSUE TITLE
Password reset requires a valid password

### ISSUE THREAD

**Issue by chozabu** [sunscrapers/djoser#134]
So - perhaps I am missing something, but this seems a bit silly

> return (u for u in active_users if u.has_usable_password())

should just be:

> return (u for u in active_users)

I mean - why would you _not_ want someone with a missing/broken password to be able to reset their password?

usecase where this is a problem:
1. account created by social auth
2. account imported from elsewhere
3. account created without password, expecting a user to reset

**Comment by chozabu** [comment]
I should say - no offence intended, there may be a very good reason for making sure the user has a workable password - just no clue what it is!

**Comment by jschneier** [comment]
I believe the logic was copied from Django itself which has the same behavior. [See for yourself](https://github.com/django/django/blob/efa9539787dbdd06cd2169023edcf7db3e2ff0c4/django/contrib/auth/forms.py#L235).

**Comment by chozabu** [comment]
Seems like a strange default - though I see it mentioned they are expecting people to override that method. I still think it is not the best default, but I'll drop this issue for now, and perhaps take it up with django in the future.
