### ISSUE TITLE
Clarification about REQUIRED_FIELDS

### ISSUE THREAD

**Issue by esistgut** [sunscrapers/djoser#136]
If I am not misunderstanding something In the default behaviour REQUIRED_FIELDS usage [should be limited to createsuperuser](https://docs.djangoproject.com/en/1.9/topics/auth/customizing/#django.contrib.auth.models.CustomUser.REQUIRED_FIELDS).
In djoser this seems to be used in non super user registrations too, how can I specify required fields for users registration without forcing them on super users too?

**Comment by piotr-szpetkowski** [comment]
I believe that the solution which would cover most use cases would be to drop `REQUIRED_FIELDS` use and displace the responsibility into custom serializers provided via [SERIALIZERS setting](http://djoser.readthedocs.io/en/latest/settings.html#serializers).

**Comment by piotr-szpetkowski** [comment]
As of the daa3c7de17642e605e5c519f12c06aad87cc1868 - after 2.0 is released you will need to override the serializer using inheritance and the [SERIALIZERS setting](http://djoser.readthedocs.io/en/latest/settings.html#serializers) mentioned above.
