### ISSUE TITLE
need new release to have a pip install in agreement with master repo 

### ISSUE THREAD

**Issue by codegastudio** [sunscrapers/djoser#137]
Hello,

Am i the only one who don't have the version with SERIALIZERS configuration in project setting with pip install ?

Thanks,
Mathieu

**Comment by GauravButola** [comment]
Spent a good half an hour thinking why it would not work for me. Apparently it's not released yet. You can still use the latest version by pointing `pip install` to github.

It'll be great if they can release it though :)

**Comment by lwm** [comment]
Have you tried using the following:

```
pip install -I -e git+https://github.com/sunscrapers/djoser.git#egg=djoser
```

Are you still having this issue then?

**Comment by codegastudio** [comment]
@lwm i have install it with a cmd like that but it's not the problem.
pip install command is here to help us to install easily some project.
i could also spend my time to dl directly all github or use pip with all option available but this not the goal.
files are on the master repo. 
they just need to be released and tagged.
regards

**Comment by lwm** [comment]
@codegastudio 

I understand - and you are right! I think releases have been slow. I am currently trying to see if the current maintainers are open to allowing more people to help. 

We all need to push for a new release.

There is no `pip` issue here (which the title suggests). So I would still recommend closing this and opening a new issue, or renaming this and continuing here.

**Comment by codegastudio** [comment]
@lwm ok with this title ?

**Comment by lwm** [comment]
@codegastudio

Awesome, thank you. Fingers crossed for a release plan!

**Comment by m-nako** [comment]
Version 0.5.0 including `SERIALIZERS` is now released. Please also note that we have dropped support for Python 2.6 and Django 1.6 and 1.7.

Thanks a lot for pushing for a new release!
