### ISSUE TITLE
User Activation URL

### ISSUE THREAD

**Issue by gulfpearl** [sunscrapers/djoser#142]
Right now I have, as per the docs, the following in settings.py:

```
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
```

Where does the uid and token get passed into ActivationView?

**Comment by lwm** [comment]
@gulfpearl 

The `ActivationSerializer` subclasses `UidAndTokenSerializer` ([source](https://github.com/sunscrapers/djoser/blob/73c2451e2dc3713436ba5a1a473d255be5953710/djoser/serializers.py#L101)) which validates the `uid` and `token` and then provides them to the view, in the `validated_data`, which is an attribute of the `serializer` ([source](https://github.com/sunscrapers/djoser/blob/73c2451e2dc3713436ba5a1a473d255be5953710/djoser/views.py#L181))

Make sense?

**Comment by piotr-szpetkowski** [comment]
Hi. Seems like this issue can be closed as there hasn't been anymore questions. A bit late, but thanks @lwm for taking care of it.
