### ISSUE TITLE
Rest-Framework webview - logout is not supported? 

### ISSUE THREAD

**Issue by pik** [sunscrapers/djoser#149]
So using the built in authentication (enabled via..): 

``` python
url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
```

I am able to login and logout from the web-view. 
![screenshot from 2016-05-26 13-08-35](https://cloud.githubusercontent.com/assets/10236920/15564297/41b36264-2343-11e6-9162-281c4a8960cc.png)
![screenshot from 2016-05-26 13-08-50](https://cloud.githubusercontent.com/assets/10236920/15564302/45d4bb54-2343-11e6-8a04-8270f1f2246f.png)

In contrast using `djoser` with the `restframework.authtoken` following the instructions in the README does not appear to provide a method for logging out from an existing session view the web-view: 

``` python
    url(r'^auth/', include('djoser.urls')),
    url(r'^auth/', include('djoser.urls.authtoken'))
```

![screenshot from 2016-05-26 12-52-24](https://cloud.githubusercontent.com/assets/10236920/15564310/6711d446-2343-11e6-86e9-14ccdc594bc6.png)
![screenshot from 2016-05-26 12-59-00](https://cloud.githubusercontent.com/assets/10236920/15564311/6b576c82-2343-11e6-8eeb-3027c05b6791.png)

**Comment by mewald1** [comment]
push

**Comment by zefciu** [comment]
Logout view is supported in ``/token/logout``. Not sure if this ticket was created before it was added, closing, however.
