### ISSUE TITLE
Is authorization token expiration implemented?

### ISSUE THREAD

**Issue by stugots** [sunscrapers/djoser#15]
The readme says, "In other words, users have been granted access to a specific resource for a fixed time period."  Where is token expiration implemented?

**Comment by konradhalas** [comment]
You have totally right @stugots - our documentation is confusing in this point. We don't have any token expiration mechanism right now, so I removed this sentence.

**Comment by khashashin** [comment]
@stugots  @konradhalas  Do you guys have any example how this could be done? It would help me a lot.
