### ISSUE TITLE
No src arch with 0.2.0 version uploaded on pypi

### ISSUE THREAD

**Issue by kmmbvnr** [sunscrapers/djoser#16]
Also lastest version on pypi 0.2.0 - https://pypi.python.org/pypi/djoser/0.2.0, there is no tar.gz source archive attached

    $ pip install djoser==0.2.0
    Downloading/unpacking djoser==0.2.0
         Could not find a version that satisfies the requirement djoser==0.2.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.1.0)
     Cleaning up...
     No distributions matching the version for djoser==0.2.0

**Comment by konradhalas** [comment]
@kmmbvnr thank you for reporting issue! It should be ok now.
