### ISSUE TITLE
Using HTML templates

### ISSUE THREAD

**Issue by RobertBroersma** [sunscrapers/djoser#166]
Hi! This library has helped me tons, but now I would like to use html email templates.

I was looking around and found #48 , looked at the code, but however am still not able to figure out how to properly use my own custom html templates!

Would anyone be so kind to point me in the right direction?

Thanks!

**Comment by lwm** [comment]
@RobertBroersma I haven't tried it but you need to pass a `html_body_template_name` argument to the `send_email` function. Give https://github.com/sunscrapers/djoser/commit/5c8ac84b58db46d0915c275ff18b8d6e84b5f9c3#diff-15ca6f395cbd2d4ecb06d565699f1d43R41 another look.

**Comment by RobertBroersma** [comment]
I'm not seeing straight or I'm not sure if I get it. Where would I use this `send_email` function? Do I override a view just as #48  ?

**Comment by lwm** [comment]
Try to follow the [customization guidelines](https://github.com/sunscrapers/djoser#customization).

**Comment by RobertBroersma** [comment]
I did it like this in the end and it works. Is this the/a right way to do it?

```python
class CustomRegistrationView(djoser_views.RegistrationView):

    def send_activation_email(self, user):
        email_factory = utils.UserActivationEmailFactory.from_request(self.request, user=user)
        email_factory.html_body_template_name = 'activation_email_body.html'
        email = email_factory.create()
        email.send()
```

**Comment by haxoza** [comment]
@RobertBroersma thanks for sharing your findings how to customise email sending.

TBH it would be good to prepare better documentation for that.

**Comment by RobertBroersma** [comment]
Scratch part of my previous comment. Django console mail backend was printing both email alternatives text and HTML to my console. I never worked with it so it was unexpected for me. 

Now that I'm using SendGrid it would send my HTML alternative as Text email.
