### ISSUE TITLE
Signals for each action

### ISSUE THREAD

**Issue by kowsari** [sunscrapers/djoser#169]
It would be nice to be able to receive signals for each of the operations that is handled by djoser. This way the app that is using djoser can do logging of what is happening. For example a user reset their password. DJoser doesnt do logging by itself, so it would be good for the app to log this in the server logs (for debugging purposes).

**Comment by piotr-szpetkowski** [comment]
I think that in future we would rather abandon the signals concept and focus on providing expandable and consistent abstractions, so you could simply and explicitly override just what you need. Right now it's just internal drafts, so it's not something that you should expect to arrive quickly.

Btw. logging is a great idea and I'll add an issue for that.
