### ISSUE TITLE
Missleading override URL README.md reset/confirm

### ISSUE THREAD

**Issue by maxblax** [sunscrapers/djoser#175]
README.md Line 153
Missleading override endpoint:

Should be
url(r'^auth/password/reset/confirm', djoser.views.PasswordResetConfirmView.as_view()),

instead of 
url(r'^auth/password/confirm', djoser.views.PasswordResetConfirmView.as_view()),

**Comment by haxoza** [comment]
@maxblax thanks for subbmiting!
