### ISSUE TITLE
Why creating this repo since djang-rest-auth exists to serve the same need ?

### ISSUE THREAD

**Issue by amineparis** [sunscrapers/djoser#184]
this will disperse opensource workforce :(

**Comment by piotr-szpetkowski** [comment]
Just like there are multiple open source REST API frameworks there are also multiple libraries that basically have the same target, however each of these tools has different scope and different vision. It's also worth noting that competition has always been a great fuel for progress - be it commercial project or OSS.

**Comment by amineparis** [comment]
It's worth manythings. dispersing workforce for example.
