### ISSUE TITLE
Race condition in case of near simultaneous POST API calls

### ISSUE THREAD

**Issue by piotr-szpetkowski** [sunscrapers/djoser#190]
Some of Djoser views are vulnerable to a race condition (which is not really a security issue unless you've setup debug in production). Basically saying, the problem is that in case of near simultaneous requests to endpoint with a POST method, which creates object for a model with a field with unique constraint, it will result in an `IntegrityError` and will return 500 to the client. 

It happens because of mentioned race condition, where validation step passes for both requests and than it fails on transaction to database.

**Comment by haxoza** [comment]
@piotr-szpetkowski do you know any steps to reproduce it with the test project in the repo?

**Comment by piotr-szpetkowski** [comment]
Yes - actually it's very easy to reproduce the issue:

1. Clone the djoser repo and setup venv with necessary requirements for testproject i.e. Django + DRF + requirements.txt + run migrations
2. `./manage.py runserver` and in the other terminal emulator window / tab run following command (provided example for httpie):
```
http -v POST http://localhost:8000/auth/register/ email=foo@spam.bar username=foo password=bar & http -v POST http://localhost:8000/auth/register/ email=foo@spam.bar username=foo password=bar
```

First request (whichever it happens to be) will respond with `HTTP/1.0 201 Created` and the second will output `HTTP/1.0 500 Internal Server Error`.
