### ISSUE TITLE
webmaster@localhost

### ISSUE THREAD

**Issue by pkyalo** [sunscrapers/djoser#202]
How can I override this default send from email?

**Comment by KaczuH** [comment]
@pkyalo set desired email address in `DEFAULT_FROM_EMAIL`
https://docs.djangoproject.com/en/1.11/ref/settings/#default-from-email

**Comment by piotr-szpetkowski** [comment]
Probably worth mentioning in our docs that our email factory respects `DEFAULT_FROM_EMAIL` Django setting.

Also there is a possibility to simply fill `from_email` parameter when manually creating email factory objects via `__init__` or `from_request`.

**Comment by pkyalo** [comment]
Thank you guys. It worked !

Steven Kyalo,

*Software Developer (Full Stack ),*

Mobile: (+254) 724 230 064

Location: Nairobi, Kenya.

On Wed, Jun 21, 2017 at 4:44 PM, Piotr Szpetkowski <notifications@github.com

**Comment by piotr-szpetkowski** [comment]
Fixed with 0a4280c1542a34ae6ad642082a041f7de59ad2f9
