### ISSUE TITLE
Drop support for Django < 1.11

### ISSUE THREAD

**Issue by piotr-szpetkowski** [sunscrapers/djoser#217]
With this baitclick title I'd like to start a discussion on when we should drop the support for Django version less than 1.11. My first and most realistic proposition is to wait until 1.8 extended supported is dropped to ensure that everyone has time to update, however maybe we should speed it up slightly e.g. few months before 1.8 death? Everyone that cares about having latest and greatest versions will probably want to upgrade Django to 1.11.x LTS as well anyway. 

Obviously, even when we drop support for particular Django versions everyone will still be able to use versions of djoser compatible with these versions - it's just not recommended to do so, because one does not receive any fixes that way.

As to why it would be convenient - supporting multiple Django versions makes development slower, we could drop few compatibility tweaks, simplify tests, speed up CI etc.

**Comment by pawelswiecki** [comment]
I'm all for pushing to the newest versions of Django. Having said that, I think we shouldn't drop support for LTS Django before it's support period. People won't be happy with it. We should synchronize with Django release cycle, at least to some extent.

**Comment by bartoszgrabski** [comment]
@pawelswiecki My thoughts exactly. I think it would be most professional to always support the versions of Django which are officially supported at given point in time.

**Comment by piotr-szpetkowski** [comment]
So, we will simply keep track of Django supported versions:
- 1.8 will keep being support until at least April 2018
- 1.10 support will end at December 2017

Thanks you guys for contributing to the discussion.
