### ISSUE TITLE
PasswordResetView proposal to move the User.is_active check from database to Python

### ISSUE THREAD

**Issue by davidtgq** [sunscrapers/djoser#223]
Something like this:

```
class PasswordResetView(utils.ActionViewMixin, generics.GenericAPIView):
    def get_users(self, email):
        if self._users is None:
            active_users = User._default_manager.filter(
                email__iexact=email,
                # is_active=True, <--- v0.6 code
            )
            # self._users = [u for u in active_users if u.has_usable_password()] <--- v0.6 code
            self._users = [u for u in active_users if u.is_active and u.has_usable_password()]
        return self._users
```

Here are the reasons:

1. If `is_active` is not True, then this opportunity can be used to notify the user that they've already registered an account with that email address, and [offer to] resend the activation email.

```
_users = User._default_manager.filter(email=email)
self._users = []
for u in _users:
    if u.has_usable_password():
        if u.is_active:
            self._users.append(u)
        else:
            # TODO resend activation email
```

2. I think with the v0.6 code, there will be some conflict if `is_active` is implemented in a model like this:

```
class User(AbstractBaseUser):
    score = models.SmallIntegerField(default=0)
    status = models.SmallIntegerField(default=0)
    email = models.CIEmailField(unique=True)
    name = models.CITextField()
    ip = models.ArrayField(models.GenericIPAddressField(unpack_ipv4=True))

    objects = UserManager()

    USERNAME_FIELD = 'email'

    @property
    def is_active(self):
        # FIXME can't do this, djoser uses .filter(is_active=True)
        return self.status > 0

    @is_active.setter
    def is_active(self, value):
        if value is True:
            self.status = abs(self.status or 1)
        elif value is False:
            self.status = -abs(self.status or 0)
        else:
            self.status = value
```
3. Any concerns about performance/inefficiency of retrieving unnecessary rows from the database should be nominal in real-world usage because there wouldn't be very many unactive accounts tied to a single email address in most cases. And again, if the activation email resend is implemented, then the retrieval of these rows wouldn't be considered wasted.

**Comment by piotr-szpetkowski** [comment]
Hi. At the first glance your proposition seems very interesting and I thought that we might go along with something like this. However - after taking a deeper look into the djoser codebase I'm afraid that there is a bigger problem in djoser codebase.

We are making an assumption that `is_active` field (or property) exists, which is plain wrong, because `AbstractBaseUser` model class which we support does not require its implementation to provide this field. Therefore, instead of going your way I think that we need to figure out some other, more flexible solution to this problem, because at the moment djoser is simply broken for some users.

One of simple solutions that came to me is to kinda go the way you have proposed, but to require custom `User` models to include the `is_active` field or property.

**Comment by davidtgq** [comment]
`AbstractBaseUser.is_active = True` is a default boolean value for the class:

```
class AbstractBaseUser(models.Model):
    password = models.CharField(_('password'), max_length=128)
    last_login = models.DateTimeField(_('last login'), blank=True, null=True)

    is_active = True

    REQUIRED_FIELDS = []
```

**Comment by piotr-szpetkowski** [comment]
Yes, you are right. I had a modified version of Django locally and I totally forgot about it, when I was looking into sources.

To sum it up shortly - `is_active` can be a field or a property or a class attribute and indeed it is quite naive to just fetch it with an ORM. Are you willing to work on a PR or should I take it from here?

**Comment by davidtgq** [comment]
I'm glad to do it :)

https://github.com/sunscrapers/djoser/pull/225

I don't know if the style for the new variable names etc. is acceptable, feel free to change them as necessary.

**Comment by piotr-szpetkowski** [comment]
I believe that with #225 merged we can mark this issue as closed?

**Comment by davidtgq** [comment]
Yes, this can be closed. Thank you for the awesome feedback, it's been a pleasure :)

**Comment by piotr-szpetkowski** [comment]
Same here, in case of any doubts do not hesitate to start a new issue and again - thank you for reporting and working on the issue.
