### ISSUE TITLE
Incompatible API changes

### ISSUE THREAD

**Issue by jeremy-carbonne** [sunscrapers/djoser#226]
It would be necessary to upgrade to a MAJOR version when you make incompatible API changes
(I had not blocked the version in a requirements.txt and i had some trouble with the latest version)

**Comment by piotr-szpetkowski** [comment]
Hi.
Yes, you are right that usually with breaking API changes one should release a new major version, however:
1. This is still an alpha version as described in package classifiers.
2. We adhere to semantic versioning:
```
Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
```
3. We are still a few steps away from releasing 1.0 which would imply stable API.

Therefore, unfortunately we might have some API breaking changes, before 1.0 release.

**Comment by piotr-szpetkowski** [comment]
No longer an issue with 1.0.0 release.
