### ISSUE TITLE
How do I disable registration?

### ISSUE THREAD

**Issue by r3econ** [sunscrapers/djoser#228]
I was looking into djoser settings but there is no options (http://djoser.readthedocs.io/en/latest/settings.html)

I also tried using Django's `REGISTRATION_OPEN` but it didn't work
```
DJOSER = {
    'REGISTRATION_OPEN': False,
}
```
Is there a way to disable registration?

**Comment by piotr-szpetkowski** [comment]
Hi.
Right now there is no setting, which would allow you to disable registration. Depending on your needs, you could for example simply include djoser URLs manually and omit the registration pattern. You could also override the [UserRegistrationSerializer](https://github.com/sunscrapers/djoser/blob/master/djoser/serializers.py#L34) with custom `validate` and always return `ValidationError` with a desired message and use the [serializers setting](http://djoser.readthedocs.io/en/latest/settings.html#serializers).

**Comment by r3econ** [comment]
Thanks for the hints. I ended up adding the urls manually. Works like a charm.
 
```
from djoser.views import LoginView, LogoutView

# Add view patterns
view_patterns = [
    url(r'^auth/login/$', LoginView.as_view()),
    url(r'^auth/logout/$', LogoutView.as_view()),
]

urlpatterns += format_suffix_patterns(view_patterns)
```
