### ISSUE TITLE
No JWT module and no login/logout endpoints found.

### ISSUE THREAD

**Issue by igsm** [sunscrapers/djoser#233]
Hi. I have been following instructions in the documentations however, I encountered the following problems.

1) login/logout paths are not found (auth/login or auth/logout). This is strange, because normally I can find them in the djoser package itself, in authtoken.py, right?
2) when I also tried to add jwt module in the urls.py, it could not be found. 
_`No module named 'djoser.urls.jwt'`_
Actually, I cannot find it in the package. I had djangorestframework-jwt installed on the project level. I tried even to remove it and install it again, but it did not help.

I was just about to get a relief on this auth topic, especially email activation, but not... issues like in other packages. Do you have any ideas what might be happening?

**Comment by haxoza** [comment]
My best guess is that you installed djoser from pypi (via pip) which is the latest released version that didn't officially support JWT yet (though it is possible to integrate it manually and it works).

We're working on JWT integration and it works in master branch on github. However it's not released yet to pypi. Hopefully we will do that very soon (maybe even tomorrow!).

**Comment by igsm** [comment]
Cool! Thanks for the quick update.

**Comment by piotr-szpetkowski** [comment]
Hi, we've released 1.0.0 so everything should just work if you update djoser from PyPI. In case of any problems, please report them via github issues.
