### ISSUE TITLE
PasswordResetEmail using wrong URL from settings

### ISSUE THREAD

**Issue by joncurrier** [sunscrapers/djoser#237]
In version 1.0.0, the `PasswordResetEmail` class in `email.py` is passing the wrong URL in the template context. It's using `ACTIVATION_URL`, but should be using `PASSWORD_RESET_CONFIRM_URL`.

**Comment by haxoza** [comment]
Thanks @joncurrier! You're correct! We will fix it asap!

https://github.com/sunscrapers/djoser/blob/master/djoser/email.py#L35

**Comment by haxoza** [comment]
@joncurrier fixed in master branch for now. Please use github version until we release updated version to pypi.

**Comment by piotr-szpetkowski** [comment]
Versions 1.0.1 has been released to PyPI.
I apologize for the mistake and thank you for reporting the issue.
