### ISSUE TITLE
Custom email templates

### ISSUE THREAD

**Issue by amuttsch** [sunscrapers/djoser#239]
Hi,

I was wondering how I can use custom mail templates for user activation, password reset and confirmation.

django-templated-mail uses `get_template()` to get the template file. I tried adding a global template file `templates/email/password_reset.html` in my root project folder and setting the `'DIRS': ['templates']`  option, but djoser still get the template from the library, not my custom one. When using the django shell (`python manage.py shell`) and typing `get_template('email/password_reset.html')`, my custom template is returned.

Is there a way to easily override the mail templates?

Thank you!

**Comment by piotr-szpetkowski** [comment]
Hi @amuttsch 
Just a quick guess, but you might need to replace `'DIRS': ['templates']` with `'DIRS': [BASE_DIR + 'templates')]`.
Also, please make sure you are using latest djoser / django-templated-mail setup with `pip install -U djoser`.

If this will not help, please provide more details about your project layout, requirements installed in your venv and settings.

**Comment by amuttsch** [comment]
It works, thank you for your quick reply :) I forgot to add the `BASE_DIR`, now I receive my custom mail template.

**Comment by Bearbobs** [comment]
same issue @ironwebstar, did you find a fix?

**Comment by stfenjobs** [comment]
same issue @ironwebstar, @Bearbobs      did you find a fix?

**Comment by stfenjobs** [comment]
i fix, becase my forgot change custom templates content

my config:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
      ...  ... 

```

file local:
`projectName/templates/email/password_reset.html`

**Comment by Bearbobs** [comment]
I have overridden the base class and changed the Email config for activation mails in Djoser config inside settings.py

**Comment by tomwojcik** [comment]
@stfenjobs have you seen [djoser docs on djoser settings](https://djoser.readthedocs.io/en/latest/settings.html#email)?
