### ISSUE TITLE
Proper way to upgrade from 0.7.0 to 1.0.1?

### ISSUE THREAD

**Issue by YPCrumble** [sunscrapers/djoser#240]
Hi - thanks for building Djoser - it's a great little library! It would be helpful in the Changelog to show breaking changes, or to show a note or two on upgrading from version to version. I used to use the various `authtoken` URLs in my app, but now it appears there is only one available - `/auth/token/create`. 

Is there a new way of performing actions like password reset and creating a new user? `/auth/token/create` only appears to replace the old `/auth/login` URL. 

Happy to add this to the changelog if I could get a little guidance on how to update for the latest version :).

**Comment by piotr-szpetkowski** [comment]
Hi.
I'd love to write a migration guide like [django-filter](https://django-filter.readthedocs.io/en/master/guide/migration.html) has done it, but unfortunately, recently I've been extremely spare on time.

To answer your questions:
1. User registration has been mostly just renamed into [user-create](http://djoser.readthedocs.io/en/latest/base_endpoints.html#user-create) just to be a little more RESTful. I believe that [password reset](http://djoser.readthedocs.io/en/latest/base_endpoints.html#reset-password) is pretty much the same it was.
2. The way you use the URLs has changed slightly to make it more granular as we have added JWT support. You want to make sure that you always include the base URLs with `url(r'^auth/', include('djoser.urls'))` as written in [getting-started](http://djoser.readthedocs.io/en/latest/getting_started.html#configuration)

Thank you for bringing this problem to my attention, I'll post a migration guide as soon as I'll have a spare hour to work on it.

**Comment by YPCrumble** [comment]
@piotr-szpetkowski thanks for your response! I see - it's only a small change. I think the biggest thing that would have helped me realize what was changing would be just a couple lines in the docs. I'll do a quick PR to show you what I mean.

**Comment by piotr-szpetkowski** [comment]
@YPCrumble proper migration guide has been published with 6c2b1b17c28ff78036bd3aeb72483032fbf84980.

You can find it at http://djoser.readthedocs.io/en/latest/migration_guide.html
