### ISSUE TITLE
user fields-need to store more than just required fields

### ISSUE THREAD

**Issue by leferaycloud** [sunscrapers/djoser#249]
Djoser does not allow saving extra user fields like first name, last name UNLESS they are REQUIRED.

Can we have it save additional fields if I am using a custom user model?

**Comment by piotr-szpetkowski** [comment]
Hi.
Please refer to #136 - it has already been reported, however the problem have not been resolved yet. For now you can resolve the issue by overriding `UserSerializer` and `UserCreateSerializer` with whatever you need and use the [SERIALIZERS setting](http://djoser.readthedocs.io/en/latest/settings.html#serializers). Closing as duplicate.
