### ISSUE TITLE
404 error with /auth url since I've upgraded from 0.7.0 to 1.1.5

### ISSUE THREAD

**Issue by h4k1m0u** [sunscrapers/djoser#256]
Hi,

I had the exact same project (before I downgraded to confirm that the problem was caused by the version 1.1.5 of Djoser) on my local machine and on a remote machine. But this same code worked well on the 0.7.0 (on my local machine), but not on the remote server which was setup recently with Djoser 1.1.5. I'm on `Django-2`, but that didn't really cause any problem with `Djoser-0.7.0`.

It's basically just a token authentication. Below is the content of my project's `urls.py`:

```python
url(r'^api/', include(router.urls)),
url(r'^api/auth/', include('djoser.urls.authtoken')),
```

On the newest version of `Djoser`, when I go to `/api/auth/login/` it throws a `404 error`. But since I down-graded, that error disappeared. This means that it's either caused by something that was added in the newer version, or simply the configuration should be changed?

I'm following the documentation to configure the routes above. However I've noticed in the video on Github that there were other lines to add as well (related to `jwt`). Are these necessary?

Thanks.

**Comment by piotr-szpetkowski** [comment]
Hi @h4k1m0u.
I believe that [migration guide](http://djoser.readthedocs.io/en/latest/migration_guide.html) might be what you are looking for.

**Comment by h4k1m0u** [comment]
Hi @piotr-szpetkowski,

Thanks for your response.
Yeah you were right, I need to update the url and the one corresponding to `urls/base.py`.
I'm wondering is it necessary to call the `logout` (`token/destroy`), when working from a javascript webapp or an Android app?

**Comment by piotr-szpetkowski** [comment]
> I'm wondering: is it necessary to call the logout (token/destroy), when working from a javascript webapp or an Android app?
If I understood question correctly - well, it depends. Some web/mobile apps do not provide an explicit logout and just wait for token to expire to renew automatically (especially when you're using JWT) or to make user provide his credentials again, so theoretically you do not have to use the logout feature if it's not in scope of your project.

> I've noticed that the token changes on every login, as opposed to before when I was getting the same token everytime I authenticated.
Interesting, thanks for the information.
