### ISSUE TITLE
last_login not set via POST /api/v1/authorization/token/

### ISSUE THREAD

**Issue by wiesson** [sunscrapers/djoser#261]
If I request a token via `POST /api/v1/authorization/token/` (which is a login in my case), the `last_login` field of the User model will not be updated or set in the first place. Is this intended?

**Comment by oliver-zhou** [comment]
I think this has been an issue since #53 , would love to see it fixed or set as well

**Comment by AlexDaniel** [comment]
Weird. It's not working for me.

**Comment by AlexDaniel** [comment]
Ah. OK, it is not really related to djoser in my case. [This](https://stackoverflow.com/a/62980267/2698019) helped. Nevermind!
