### ISSUE TITLE
Custom user, auth with email

### ISSUE THREAD

**Issue by farzeni** [sunscrapers/djoser#270]
Hello, 
First, thanks for your work!

I have a problem during user registration using a custom user model with USERNAME_FIELD as email
User is defined as follow:

```python
class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    email = models.EmailField(max_length=70, unique=True)
```

test case:
```python
    def test_register_user(self):
        url  = reverse('user-create')
        data = {
            'email': "joe@smith.it",
            'password': 'testtest20',
        }
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
```

When I test user creation, an Exception is raised:

```
[...]
  File "/home/fabri/.virtualenvs/test/lib/python3.5/site-packages/djoser/views.py", line 61, in perform_create
    user = serializer.save()
  File "/home/fabri/.virtualenvs/test/lib/python3.5/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/home/fabri/.virtualenvs/test/lib/python3.5/site-packages/djoser/serializers.py", line 63, in create
    user = self.perform_create(validated_data)
File "/home/fabri/.virtualenvs/test/lib/python3.5/site-packages/djoser/serializers.py", line 71, in perform_create
    user = User.objects.create_user(**validated_data)
TypeError: create_user() missing 1 required positional argument: 'username'
```

I get the same error also if i pass username as post value:
```python
    def test_register_user(self):
        url  = reverse('user-create')
        data = {
            'username': "joe",
            'email': "joe@smith.it",
            'password': 'testtest20',
        }
        response = self.client.post(url, data)
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
```

My env is: 
Django 1.11.8
DRF: 3.7.7
Djoser: 1.3.0

Am I missing something?

Thanks

**Comment by adamshamsudeen** [comment]
I also got the same error, I fixed it by passing the email also to the username field. It seems that Django admin is expecting a username field nevertheless. To completely overcome it, we might need to use AbstarctBaseUser and rewrite the User Model.

I'm not sure though, this is the workaround I found.

`
class User(AbstractUser):

	email 			 = models.EmailField(max_length=254, unique=True)
	phone_number 	 = models.CharField(max_length=120)
	country 		 = models.CharField(max_length=120)
	state 			 = models.CharField(max_length=120)
	city			 = models.CharField(max_length=120, null=True, blank= True)
	postcode 		 = models.CharField(max_length=120, null=True, blank= True)
	company  		 = models.CharField(max_length=120)
	position 		 = models.CharField(max_length=120)
	company_profile  = models.CharField(max_length=120, null=True, blank= True)
	
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username','phone_number','country','state','city','postcode','company','first_name']
`


`
curl -X POST http://127.0.0.1:8000/auth/users/create/ --data 'username=dj@tst.com&password=nottherealone&email=adam@gmail.com&country=India&phone_number=98099802734&username=adam@gmail.com&state=kerala&city=alapuzha&postcode=1234234&company=Microsoft&position=CEO&first_name=Jon Snow'
`

**Comment by farzeni** [comment]
Hi @adamshamsudeen, thanks for your reply.

Actually I found another way to solve it overriding create_user and create_superuser in UserManager.

```python

class UserManager(DjangoUserManager):
    def create_superuser(self, username=None, email=None, password=None, **extra_fields):
        if not username and not email: 
            raise Exception("You must define username or email")

        if not username and email: 
            username = email
        
        return super(UserManager, self).create_superuser(username, email, password, **extra_fields)
    def create_user(self, username=None, email=None, password=None, **extra_fields):
        if not username and not email: 
            raise Exception("You must define username or email")

        if not username and email: 
            username = email
        
        return super(UserManager, self).create_user(username, email, password, **extra_fields)

    def get_by_natural_key(self, username):
        return self.get(
            models.Q(**{self.model.USERNAME_FIELD: username}) |
            models.Q(**{self.model.EMAIL_FIELD: username})
        )

class User(AbstractUser):
    class Meta:
        app_label = 'organizations'

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
    email = models.EmailField(max_length=70, unique=True, db_index=True)

```
I'm not sure that it is the right way to go but it seems to solve my issue without having to manage username field manually.
