### ISSUE TITLE
Make trailing slash optional in url routes

### ISSUE THREAD

**Issue by eschercode** [sunscrapers/djoser#273]
[Back in 2013](https://github.com/encode/django-rest-framework/issues/905) DRF added support to optionally exclude the trailing slash from url routes. Though Django url conventions use a trailing slash, many Google tools don't work with them (Angluar, Chrome browser APIs...), and if you rely on using `APPEND_SLASH = True` in your Django settings, you lose the POST data during the redirect.

The djoser urls all have a compulsory trailing slash, but I can't use djoser with with Chrome's `fetch()` browser API, because it strips the trailing slash when making the request. At the moment I'm using a forked djoser with modified urls.

Obviously the url regex can be modified to include `[/]` at the end as an easy fix, but is it worth putting a TRAILING_SLASH setting in to gain explicit control over if it is permitted?

**Comment by zefciu** [comment]
Could you post your changes as a PR?

**Comment by eschercode** [comment]
I'm pretty sure this change was already incorporated several versions ago?

**Comment by zefciu** [comment]
Yes. I also see that the slash is optional in the routes. Closing then.

**Comment by mrcoles** [comment]
How is the trailing slash optional? This is the [base.py](https://github.com/sunscrapers/djoser/blob/master/djoser/urls/base.py) file in djoser:

```python
from django.contrib.auth import get_user_model
from rest_framework.routers import DefaultRouter

from djoser import views

router = DefaultRouter()
router.register("users", views.UserViewSet)

User = get_user_model()

urlpatterns = router.urls
```

The slashes in URLs are determined by the `rest_framework.routers.DefaultRouter` class, which can receive an optional boolean argument of `trailing_slash`. From [their docs](https://www.django-rest-framework.org/api-guide/routers/#defaultrouter):

> As with SimpleRouter the trailing slashes on the URL routes can be removed by setting the trailing_slash argument to False when instantiating the router.

What is the potential change that includes this? Is it being confused with django’s auto-redirect to slashes?

---

A potential PR would look something like this:

base.py:

```python
from djoser.conf import settings

…
router = DefaultRouter(trailing_slash=settings.ROUTER_TRAILING_SLASH)
…
```

conf.py:

```python
default_settings = {
    …,
    "ROUTER_TRAILING_SLASH": True,
    …,
}
```
