### ISSUE TITLE
Add support for BasicAuthentication backend

### ISSUE THREAD

**Issue by jxstanford** [sunscrapers/djoser#28]
I'm hesitant to call this an issue -- more of a curiosity.  Was there a reason that you chose not to implement the handling of authentication for the /login endpoint via the BasicAuthentication class in DRF?

**Comment by haxoza** [comment]
We should be able to add support for BasicAuthentication quite easily. I hope we will implement and document it in the nearest future.

**Comment by haxoza** [comment]
As long as #57 is fixed and closed the support for HTTP Basic Auth is fully working.
