### ISSUE TITLE
set_username issue : cant activate account for changed email address

### ISSUE THREAD

**Issue by sandeshnaroju** [sunscrapers/djoser#284]
I am just trying all the features of Djoser. I have successfully created new user and tried to change the user email. 
I used below URL 

> http://127.0.0.1:8000/auth/email/
> Authorization: Token fed13208d853443fc7da19f025a419f14aded2aa 
> current_password : " ",
> new_email : " ",

I received a email to the changed email address. with UID and Token. 
I have copied UID and Token  and inserted in Post request of  http://127.0.0.1:8000/auth/users/activate/ ,
When I do it,

I get the following error

`{
    "non_field_errors": [
        "Invalid token for given user."
    ]
}` 

I don't know where I did wrong. I will add more information if needed.

**Comment by dekoza** [comment]
Can you please show how you did the confirmation request? Please use curl or the same method you used in first part of your report ("I used below URL").

**Comment by Pixsel1** [comment]
I see that this issue is stale. If don't, just reopen.
