### ISSUE TITLE
More than one users can be created with one email address.

### ISSUE THREAD

**Issue by rupeshcode** [sunscrapers/djoser#289]
I have been using Djoser for my project. This "big" error came while testing that more than one users can be created using the same email address but different usernames.
Please share a solution if anyone knows a way around.

**Comment by dekoza** [comment]
That is because the original User model has `unique` constrain only on `username` field, not on `email`. To get rid of this issue you'd need to make your own User model or at least UserSerializer with appropriate validator. Hope that helps.

**Comment by rupeshcode** [comment]
This has solved my problem.
but I have made the changes in Djoser. now, how can these changes be applied to my app hosted on AWS as the changes are in external library which is installed by AWS.
means how can I override my changes to installed library on AWS.
