### ISSUE TITLE
Bad translation

### ISSUE THREAD

**Issue by abaybek** [sunscrapers/djoser#291]
I found that error messages is really translated badly. Where can I translate them?

In kazakh: {"email":["қолданушы адрес электронной почты жолақпен бұрыннан бар."]}
russian: {"email":["пользователь с таким адрес электронной почты уже существует."]}
english: {"email":["user with this email address already exists."]}%

**Comment by dekoza** [comment]
We do not provide any translations but all of the strings are marked for translation. Please look into you project's files and find `locale` directory there. You can read more in [Django documentation](https://docs.djangoproject.com/en/2.1/topics/i18n/translation/).
