### ISSUE TITLE
Password reset link remains valid after usage

### ISSUE THREAD

**Issue by quantumkoen** [sunscrapers/djoser#296]
The password reset link generated by `djoser.views.PasswordResetView` remains valid after use. In fact, when requesting a password reset again, the same link is sent.

This is a bit of a security risk, because anyone with that link (even if it has been years ago that you requested a password reset) can change your password. I don't think users would expect that the link remains valid after usage, and might not be as careful with it as they should be.

Of course, the current scheme has the adventage that it is stateless on the server. A link that is invalidated after use requires some information to be stored somehow. I think it would be a trade-off i'm willing to make: some database storage for improved security.

**Comment by dekoza** [comment]
Thanks for reporting, I'll start patching it asap.

**Comment by dekoza** [comment]
`djoser` by default users `django.contrib.auth.tokens.PasswordResetTokenGenerator` and this uses last login timestamp to make the token. This assumes that user is forcibly logged in at the end of changing password. `djoser` omits the "login" part but the date should be reset anyway to simulate the login.

Aside that, if you want to make your own token generator, I can point you to one value that must be kept on server  side and that MUST change during password reset - it's the password hash :wink: If you **securely** use it to calculate the password reset token, you should get an auto-invalidated token without the need to remember to update the date or any other value.

**Comment by quantumkoen** [comment]
@dekoza Awesome, thanks for the quick and sensible follow-up!
