### ISSUE TITLE
Multiple tokens per user so one can log in and log out from different devices independently

### ISSUE THREAD

**Issue by felipemoran** [sunscrapers/djoser#30]
It would be nice if every time a user logs in a new token was generated and sent. In this way a user could log in and out on his phone without getting logged out from his computer. But because of this a new method would be necessary, that would be being able to log out from all devices (making all tokens invalid)

**Comment by konradhalas** [comment]
This is most important thing on our roadmap right now. Thank you for creating issue, I hope it will motivate us.

**Comment by felipemoran** [comment]
Great, that would be a really nice feature. Thanks!

**Comment by konradhalas** [comment]
According to decisions taken in #33 (summary: we will create separate app) I'm closing this issue.
