### ISSUE TITLE
Use different JWT package

### ISSUE THREAD

**Issue by joshua-s** [sunscrapers/djoser#302]
For all intents and purposes, django-rest-framework-jwt has been abandoned and is no longer receiving updates (https://github.com/GetBlimp/django-rest-framework-jwt/issues/449). It is a good time for djoser to consider another package for JWT authentication.

One that I found:
- https://github.com/davesque/django-rest-framework-simplejwt

**Comment by dekoza** [comment]
I'm considering removing JWT altogether. See [this discussion](https://news.ycombinator.com/item?id=13865459).

Anyway, since a lot of people do like JWT, I'll refactor the code to use some new library. Thanks for pointing that.

**Comment by joshua-s** [comment]
@dekoza if you haven't started work on this, I can take a quick stab at it. (Already patched this on two of my projects using djoser)

**Comment by dekoza** [comment]
@joshua-s please do. I have loads of work to do before I can work on this. Thanks!

**Comment by joshua-s** [comment]
Sounds great! Thanks!

**Comment by ksitko** [comment]
Has a decision been made in regards to either deprecating or making a new version to use simplejwt? Or has it been decided to eliminate JWT entirely?

**Comment by joshua-s** [comment]
@ksitko I am waiting for a review on my PR #305.

Ultimately, it might be good to define a standard interface for auth systems and then split JWT and Token auth out into separate packages. This will make us much more flexible.
