### ISSUE TITLE
Allow optional user fields to be set on registration

### ISSUE THREAD

**Issue by joshua-s** [sunscrapers/djoser#306]
It would be very helpful if optional user fields like `first_name` and `last_name` could be set in `POST /users/`. The available fields would depend on the serializer being used.

**Comment by zefciu** [comment]
@joshua-s you can set the serializer in settings. Is that what you want or do you think of some other feature here?

**Comment by joshua-s** [comment]
I can't believe I missed that. Sorry for the trouble.
