### ISSUE TITLE
Compatibility issues with Swagger

### ISSUE THREAD

**Issue by prafulbagai** [sunscrapers/djoser#31]
I integrated Djoser in my Django project. The api endpoint provided are all working fine, but when I browse to the Swagger docs, it throws the following error, saying `AssertionError: 'RootView' should either include a 'serializer_class' attribute, or override the `get_serializer_class()` method.
`

Here is the screenshot:-

![screenshot from 2015-04-12 20 35 30](https://cloud.githubusercontent.com/assets/4829481/7106079/9dc2e62a-e153-11e4-91a9-ec376cc1c145.png)

Is that a bug?

**Comment by konradhalas** [comment]
Ok, we will check that. Are you using `django-rest-swagger`? Which version?

**Comment by prafulbagai** [comment]
I'm using the latest version of django-rest-swagger. The `RootView` was a subclass of `generics.GenericAPIView`. I changed it to `APIView` and it started working fine. Let me know if it is supposed to work like this or not? Same goes for `LogoutView` as well.

**Comment by haxoza** [comment]
Thanks @prafulbagai! You're probably right. It helped with fixing #39. We will change base class of `RootView` to `APIView` soon.

**Comment by haxoza** [comment]
I tested the commit above with `django-rest-swagger` and it works fine. However I wonder if we it's worth to add some compatibility tests just for future development.

@konradhalas what do you think about that?

**Comment by konradhalas** [comment]
@haxoza do we have some easy way to check compatibility with swagger in our tests?

**Comment by haxoza** [comment]
The basic idea would be to hit the right URL to generate the JSON docs and check if it doesn't raise any exceptions.

However my only worry is that [django-rest-swagger](https://github.com/marcgibbons/django-rest-swagger) is under heavy development. There are many unresolved issues, many forks and they will be migrating to Swagger 2.0 soon. I'm afraid that it could be too big overhead to support this project continuously.

**Comment by pbdeuchler** [comment]
Hey guys, just encountered this bug. I'm experiencing the same issue, [but with `LogoutView`](http://s3.uploads.io/u/805gj2v8h6bc.png). However I checked the code and `LogoutView` seems to use `views.ApiView`... which is odd

**Comment by haxoza** [comment]
@pbdeuchler Hi! I guess you're browsing the code on Github in `master` branch which is fixed but not deployed to PyPi yet. If you want to use fixed code I recommend to install `djoser` from the latest commit. However please be aware of some small changes like trailing slashes added to urls.py.

**Comment by haxoza** [comment]
This issue is not valid anymore. Further discussion should be moved to issue #43.
