### ISSUE TITLE
CurrentUserSerializer Parent Class

### ISSUE THREAD

**Issue by nils-wisiol** [sunscrapers/djoser#312]
In [commit 82e195b](https://github.com/sunscrapers/djoser/commit/82e195b0cc4825952583c39b3e54b92bb45fbb71#diff-291a3ad79f2c557a4c22403102a542c1R36), the parent class of `CurrentUserSerializer` was changed from (djoser's) `UserSerializer` to `settings.SERIALIZERS.user`. 

Why was it changed this way? It seems to break things in our project, I believe because it causes a cyclic import. (This may be specific to our project structure.)

Pinging @joshua-s

**Comment by joshua-s** [comment]
I am very sorry for introducing this issue. It is indeed a cyclic import and we are figuring out next steps in #308.

**Comment by nils-wisiol** [comment]
Woops sorry for the dub.

**Comment by joshua-s** [comment]
No worries! The title of the other is not apparent.
