### ISSUE TITLE
social auth via github

### ISSUE THREAD

**Issue by unixconky** [sunscrapers/djoser#317]
I make this API call (GET)

`http://localhost:8000/auth/o/github/?redirect_uri=http://localhost:8000`

in the response I got:

```
{
    "authorization_url": "https://github.com/login/oauth/authorize?client_id=c34bdab4...&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fauth%2Fcomplete%2Fgithub%2F%3Fredirect_state%3D4VrTV0VFCWi83SAsbvtQl7ia&state=4VrTV0VxB9jIFCWi83SAsbvtQl7ia&response_type=code"
}
```

When I open this URL I see Github login page and then if I log in and click "Allow" button, Github redirect me to the URL provided in github app settings - `http://localhost:8000?redirect_state=4VrTV0VxfEWB9jIFCWi83...Ql7ia&code=3e88284f372eb7f28724&state=4VrTV0VxfEWB9..l7ia`

but I don't see new user in admin panel.

What I'm doing wrong?

**Comment by zefciu** [comment]
This indeed wasn't described very well in the documentation. I have corrected the docs in this PR: https://github.com/sunscrapers/djoser/pull/338

Basically, the only thing you are missing is doing the POST to the endpoint with code and state that github gave you.

**Comment by Emnalyeriar** [comment]
Hey @zefciu @dekoza 
Instead of creating a new issue I thought I'll make a follow-up questions here. I'm trying to make a POST request with `code` and `state` but I'm using Google OAuth2 as a provider.
This is the request that I'm sending:
```
General:
    Request URL: http://localhost:8000/api/v1/auth/o/google-oauth2/
    Request Method: POST
    Status Code: 400 Bad Request
    Remote Address: [::1]:8000
    Referrer Policy: no-referrer-when-downgrade
Response Headers:
    Access-Control-Allow-Origin: *
    Allow: GET, POST, HEAD, OPTIONS
    Content-Length: 53
    Content-Type: application/json
    Date: Wed, 26 Jun 2019 14:12:31 GMT
    Server: WSGIServer/0.2 CPython/3.7.2
    Vary: Accept, Cookie
    X-Frame-Options: SAMEORIGIN
Request Headers:
    Provisional headers are shown
    Accept: application/json, text/plain, */*
    Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryiossmNpU2DwEMAkU
    DNT: 1
    Origin: http://localhost:3000
    Referer: http://localhost:3000/login?state=mSykVGXLFMMqlWLNaqaqaBfWTYUPziK8&code=4%2FdAEXH3ChEzZDRWTA2JXEPwLxxWwf7h1gboCCeH0Zd_K-xhWHBNg7WLdga2GDdlo_xh5sHNt9fbKhG_ZuxYGVs8o&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&session_state=e39034a8601e1ea9813f701bbaf583b1310f9193..21d4&prompt=consent
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Form Data:
    code: 4/dAEXH3ChEzZxxxxxxxxxxxxxx
    state: mSykVGXLFxxxxxxxxxxxx
```
but in response I get this error:
`{non_field_errors: ["Session value state missing."]}`
Not sure what's wrong here - I'm sending the POST request to the same url as the previous GET request, the content type is set as in documentation to `application/x-www-form-urlencoded`.
Any thoughts what might be wrong here?

**Comment by omerwaqaskhan** [comment]
It is still really very confusing, with DRF it is getting hard to achieve social login.

**Comment by vmesel** [comment]
@Emnalyeriar do you have any update on this error?

I'm getting the same error around here!

Agree with @omerwaqaskhan, documentation is still confusing and the lack of usage examples are really anoying.

**Comment by abdulhakkeempa** [comment]
@vmesel have you found any solution for the issue?

I am also facing similar error.
