### ISSUE TITLE
sends 3 emails instead of 1 upon sending post request for password reset

### ISSUE THREAD

**Issue by lucasnoah** [sunscrapers/djoser#32]
Is anybody else experiencing this or is my Django just wanky?

My Django server output shows an options and a post request. 

[14/Apr/2015 22:27:00] "OPTIONS /auth/password/reset HTTP/1.1" 200 334
[14/Apr/2015 22:27:05] "POST /auth/password/reset HTTP/1.1" 200 0

**Comment by konradhalas** [comment]
`OPTIONS` request is used by browser to check CORS permissions - check http://en.wikipedia.org/wiki/Cross-origin_resource_sharing

Could you provide more info about emails issue? How could we reproduce it?

Please reopen issue if you provide more details.
