### ISSUE TITLE
'UserView' should either include a `queryset` attribute

### ISSUE THREAD

**Issue by atkawa7** [sunscrapers/djoser#323]
```

Request Method: | GET
-- | --
http://127.0.0.1:8000/api/v1/auth/me
2.1.3
AssertionError
'UserView' should either include a `queryset` attribute, or override the `get_queryset()` method.
C:\Python37\lib\site-packages\rest_framework\generics.py in get_queryset, line 68
C:\Python37\python.exe


```

Related commit
https://github.com/encode/django-rest-framework/commit/b3253b42836acd123224e88c0927f1ee6a031d94

**Comment by dekoza** [comment]
Thanks, missed that in tests.

**Comment by atkawa7** [comment]
@dekoza On a side note multiple  djoser views that inherit views.GenericsApiView  require this queryset

**Comment by dekoza** [comment]
I fixed the bug but the tests do not cover `/me/` endpoint as it was deprecated in version 1.2.0 and `/users/me/` should be used instead. Old endpoints are retained for backward compatibility but will be removed in 2.0.
