### ISSUE TITLE
Exposure of user pk, small security issue

### ISSUE THREAD

**Issue by gou-simada** [sunscrapers/djoser#351]
Thank you for making good app. I found small security issue.
For example, when you create account at` "/users/create/"`, you will receive this response.  

```
{
    "email": "my_name@example.com",
    "id": 1000,
    "username": "my_name"
}
```

For some developer, this become security issue:  [from security.stackexchange](https://security.stackexchange.com/questions/56357/should-i-obscure-database-primary-keys-ids-in-application-front-end#comment89550_56358)

> You would also reveal the number of IDs ..... and the current rate of creation (someone creates one, then a set time later finds the new maximum). This might be of interest in the case of user accounts, as eg. it gives clues as to the financial viability of your application to a competitor. – Julia Hayward

Can I remove user id by djoser settings ?
If no setting about this, I will write views(override djoser views) for no user id response, for private use.
someone needs this improvement?

If djoser maintainer think this is useful, and they can merge this improvement,   
I will write code and send pull request.

In that case, I will add Djoser settings as bellow ( in `settings.py` )
```
DJOSER = { 
    'RETURN_USER_ID': False, # Default is True for compatibility  
   }
````

How do you think ?  Please tell me your opinion !

**Comment by joshua-s** [comment]
Hey! I am sorry you had to wait so long for a response.

This is indeed possible. To remove the ID from the user create view, just follow these steps:
1. Switch to `POST /users/` as your user creation endpoint. `POST /users/create/` is an old endpoint that we have kept for backwards compatibility and will soon retire. It will not be receiving new features.
2. Override the default `UserCreateSerializer` in Djoser settings with your own serializer that does not include the `id` field: https://djoser.readthedocs.io/en/latest/settings.html#serializers

One other note: to mitigate that underlying issue about exposing IDs, you can use UUID4 as the ID for your user model.

If you have any questions, please post them!

**Comment by gou-simada** [comment]
Thank you for perfect answering!
