### ISSUE TITLE
Does social auth require django-rest-simplejwt?

### ISSUE THREAD

**Issue by derek-adair** [sunscrapers/djoser#352]
Just playing around with this stuff a bit and it seems that /o/google-oauth2/ returns JWT.  Propbably worth noting in the docs if I need JWT to get social auth backends working.

**Comment by rolep** [comment]
Currently djoser returns jwt for any social_auth passed user.

But you can make your TokenStrategy and return custom data / tokens.

See https://github.com/sunscrapers/djoser/issues/362#issuecomment-481293587
