### ISSUE TITLE
It's unclear what is meant by SERIALIZERS.current_user

### ISSUE THREAD

**Issue by mnieber** [sunscrapers/djoser#353]
I'm getting a deprecation warning "Current user endpoints now use their own serializer setting. For more information, see: https://djoser.readthedocs.io/en/latest/settings.html#serializers".

The referred documentation mentions that "Current user endpoints now use the serializer specified by SERIALIZERS.current_user". However, it's unclear what `SERIALIZERS.current_user` exactly refers to. Does it mean `settings.DJOSER['SERIALIZERS']['current_user']`? Or does it mean that `settings.SERIALIZERS` should point to an object that has a `current_user` member? In the latter case, I suppose `settings.SERIALIZERS.current_user` is a string that points to a serializer class?

In any case, I'm confused. Could this be clarified?

**Comment by joshua-s** [comment]
Hey @mnieber I apologize for the delay. The documentation is referring to `settings.DJOSER['SERIALIZERS']['current_user']`. This definitely needs to be clarified.
