### ISSUE TITLE
Document what happens after activation failure due to expired token

### ISSUE THREAD

**Issue by mnieber** [sunscrapers/djoser#358]
Hi, 

I'm trying to figure out what happens after the activation failed because of an expired token. Normally, the user would try to register again with the same email, but this will probably fail because the email is already used (by the inactive user that was created earlier). This means that this user should be deleted before trying the registration again.

Of course, with some digging I will be able to find it out, but would you agree that the documentation should explain to which extent Djoser helps you to cover this scenario? (even if it's just a short explanation that the developer should implement this scenario themselves)

**Comment by Pixsel1** [comment]
Everything depends on, how it should works, how you want.
I think it's clear and you just need to check out documentation:
https://djoser.readthedocs.io/en/latest/base_endpoints.html#user-resend-activation-e-mail

This what you're talking about is, I think, examples of usage or a tutorial.
