### ISSUE TITLE
Programmatically get access_token and refresh_token in view

### ISSUE THREAD

**Issue by sandeshnaroju** [sunscrapers/djoser#364]
I want to get refresh_token and access_token from **user** instance in view. How to implement it?

**Comment by Pixsel1** [comment]
You can use `rest_framework_simplejwt.tokens.RefreshToken` to get these informations

from rest_framework_simplejwt.tokens import RefreshToken

token = RefreshToken.for_user(user)

refresh_token = str(token)
access_token = str(token.access_token)


Please next time don't create issue in this place, just ask on e.g. stackoverflow or another page.
