### ISSUE TITLE
WebAuthn in Djoser- W3C standard

### ISSUE THREAD

**Issue by Kub-AT** [sunscrapers/djoser#365]
Major browsers and platforms have built-in support for new Web standard for easy and secure logins via biometrics, mobile devices and FIDO security keys.

Now WebAuthn is W3C standard:
https://www.w3.org/2019/03/pressrelease-webauthn-rec.html

**Comment by dekoza** [comment]
Thanks for reminding, I'll dive into it asap :+1:

**Comment by haxoza** [comment]
@hawi74 nice work! 👍 

However from architecture point of view and further extending this kind of backends, it would be good to confront your approach to work done in [django-trench](https://github.com/merixstudio/django-trench).

**Comment by dekoza** [comment]
I just found [pywarp](https://github.com/pyauth/pywarp) :wink:

**Comment by Sleepy105** [comment]
There is also [django-webauthn](https://github.com/shemigon/django-webauthn) which builds upon pywarp. Maybe some work can be salvaged from there. The last commit was made 10 months ago, though.

**Comment by Sleepy105** [comment]
A [issue](https://github.com/python-social-auth/social-core/issues/224) to request support in python-social-auth has also been open.

**Comment by Sleepy105** [comment]
Any progress on this issue or related PR?
python-social-auth seems to have [given up](https://github.com/python-social-auth/social-core/issues/224) on implementing this.

**Comment by hawi74** [comment]
I don't have the time or means (I was testing it on Windows 10 + IE/Edge using PIN as a "key" as I did not have any physical key, nor could I find any software-based substitute) to carry on with #427, but I can see that webauthn merged my PR so changes on #427 should work now. Feel free to take over and make any necessary adjustments, if needed.
