### ISSUE TITLE
What happened to version 1.5.0?

### ISSUE THREAD

**Issue by hvdklauw** [sunscrapers/djoser#369]
Everything was fine and working until suddenly CI started failing:

```
'Could not find a version that satisfies the requirement djoser==1.5.0 (from -r /tmp/pipenv-hb701gt2-requirements/pipenv-f66_jas5-requirement.txt (line 1)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.7.0, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.2, 1.3.3, 1.4.1, 1.5.1)
```

Please please please don't retract versions, even if they are buggy the bug might not affect me and this break consistent deploys !

Now the build that we have been testing on staging will have to be updated and retested because we need to update a package.

**Comment by dekoza** [comment]
Sorry for that but we discovered a critical bug (#366) that could escalate to editing of user profiles by logged-in users. After some discussion we decided to pull down all affected versions to enforce the update. If you have a better solution to keep our users safe from serious security issues, please let us know, We'd be more than happy to implement it.

We're really sorry for the trouble and promise to have better security tests in future.

**Comment by hvdklauw** [comment]
I understand, but it's just a hard sell to tell people you need to fix something that doesn't change anything to our security and that a retest isn't needed.

There is: https://pyup.io/safety/ which is used by `pipenv check` to check security vulnerabilities, I see djoser [in there](https://github.com/pyupio/safety-db) so that is one way to notify about issues!

**Comment by nitely** [comment]
Does Django pull down versions when a "critical" bug is discovered? who does that?
