### ISSUE TITLE
Advice: Overriding templates

### ISSUE THREAD

**Issue by LiteWait** [sunscrapers/djoser#37]
I just wanted to confirm that there isn't an easier way to customize the templates, other than:

1. Subclass the views that use templates.
2. Create and include my own version of djoser.urls

Correct?

**Comment by konradhalas** [comment]
Good question. I don't remember Django behavior here, but if you add e.g. `djoser/password_reset_email_subject.txt` into one of your `TEMPLATE_DIRS` it will override `djoser` template. Am I right?

**Comment by LiteWait** [comment]
Konrad,
Yes, I wasn't paying attention that you were using the template loader.
Thank you.
Tim

**Comment by konradhalas** [comment]
No problem. Happy to see that it works for you.
