### ISSUE TITLE
The current path, accounts.html, didn't match any of these.

### ISSUE THREAD

**Issue by jbandeiira** [sunscrapers/djoser#372]
I'm trying to target the "/ account" page after login, but give the error: The current path, accounts.html, didn't match any of these.

How can I solve?

My Project Urls (Simplex)
`from django.contrib import admin
from django.urls import path, include
from website.views import IndexTemplateView

urlpatterns = [
    path('/', IndexTemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('website.urls'), name='accounts'),
    path('admin/', admin.site.urls),
]`

My App urls (Website)
`from website.views import IndexTemplateView
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [

    # GET /
    path('/', IndexTemplateView.as_view(template_name='index.html'), name='index'),

    # GET /accounts
    path('accounts/', views.accounts, name='accounts'),`

My App View
`from django.urls import reverse_lazy
from django.views.generic import TemplateView
from simplex.models import Cliente
from website.forms import InsereClienteForm
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login
from .forms import LoginForm

# PÁGINA PRINCIPAL
# ----------------------------------------------

class IndexTemplateView(TemplateView):
    template_name = "website/index.html"

# PÁGINA LOGADO (ACCOUNTS)

def accounts(request):
    return HttpResponse('website/accounts.html')`

**Comment by Pixsel1** [comment]
I'm afraid, that it's not a problem in `djoser`.
Please ask and give more detail on e.g. stackoverflow or another page.
