### ISSUE TITLE
state of session authentication in djoser

### ISSUE THREAD

**Issue by benzkji** [sunscrapers/djoser#373]
As a DRF newbie, using djoser, but also wanting to use session auth, as my application is only browser based, I wonder why session auth is not supported by djoser, as seen here:
https://djoser.readthedocs.io/en/latest/getting_started.html#supported-authentication-backends

Then according to #320, I found the CREATE_SESSION_ON_LOGIN setting, that seems undocumented? I would gently help to improve docs, but I am wondering what exactly the current state with session auth is?

**Comment by benzkji** [comment]
for example, could I disable Token auth in DRF, and enable CREATE_SESSION_ON_LOGIN in djoser, and there we go? Or is this too simple thinking?

**Comment by dekoza** [comment]
The main point of RESTful APIs is to provide unified solution for web and mobile apps. Session handling on mobile is problematic - it is far more convenient to just

**Comment by dekoza** [comment]
Also, `djoser` will receive a cleanup and refactor in near future, stay tuned.

**Comment by benzkji** [comment]
Thank you. I dont have a mobile to be supported. Session auth is easy and works out of the box, with expire and other functionality built in by django. And is a good solution, for a plain web SPA, IMHO. Also, DRF itself supports it in core. And, it works with djoser.

Would you accept a PR that clarifies things in docs, and officialy adds support (maybe after refactor)?

**Comment by dekoza** [comment]
I can tell you if I can accept the PR only after seeing it :wink: But you are welcome to propose any changes that you see fit.

**Comment by benzkji** [comment]
sure ;-) any (non final) timeline for the refactor? for me it's not urgent, as it works as it is now.

**Comment by dekoza** [comment]
Probably mid-June 2019.

**Comment by stfenjobs** [comment]
Did you solve it ？ friend

**Comment by benzkji** [comment]
@dekoza I guess the refactor is done? any changes for session auth? would you still accept a PR? :-)

**Comment by stfenjobs** [comment]
i solved

add config：

```
DJOSER = {
  ......
    'CREATE_SESSION_ON_LOGIN': True,   
....
}

```

**Comment by benzkji** [comment]
yes. that's the current solution. officialy supporting session auth, with up to date docs, and cleaned up code, is another. let's see if I can invest some time someday

**Comment by fabtjar** [comment]
> i solved
> 
> add config：
> 
> ```
> DJOSER = {
>   ......
>     'CREATE_SESSION_ON_LOGIN': True,   
> ....
> }
> ```

@stfenjobs what end point did you use with these? `/token/login/` and `/token/login/` look like the only ones for login/logout but use tokens.

**Comment by Sergecodes** [comment]
Has this been solved already ?

**Comment by benzkji** [comment]
solved with

```
DJOSER = {
  ......
    'CREATE_SESSION_ON_LOGIN': True,   
....
}

```

this will create an auth token, though, and give it back in the response, if you dont override that serializer.
