### ISSUE TITLE
Documentation Issue - jwt verification endpoint

### ISSUE THREAD

**Issue by michealjroberts** [sunscrapers/djoser#374]
The /auth/jwt/verify endpoint throws a 401 unauthorised error, and not a 400.

<img width="1166" alt="Screenshot 2019-05-02 at 16 52 06" src="https://user-images.githubusercontent.com/23339706/57088747-daccf600-6cfa-11e9-9809-7b4fd9279bc6.png">

**Comment by dekoza** [comment]
Thank you, this will be corrected with upcoming `1.6.0` release.
