### ISSUE TITLE
Enhancement: Get domain for email from request

### ISSUE THREAD

**Issue by LiteWait** [sunscrapers/djoser#38]
We've got 100's of tenants running out of a single settings.py file.  Having settings.DOMAIN provided in settings.py is pretty limiting.  Suggestion would be to pull the domain from the request.  There may be a better way though.

Here is the change I made to utils.py

        def get_email_context(self, user):
            token = self.token_generator.make_token(user)
            uid = encode_uid(user.pk)
            # Pull domain from request
            try:
                domain = self.request.get_host()
            except:
                domain = settings.get('DOMAIN')
            return {
                'user': user,
                'domain': domain, # Use domain from request or if not provided fall back to settings.
                'site_name': settings.get('SITE_NAME'),
                'uid': uid,
                'token': token,
                'protocol': 'https' if self.request.is_secure() else 'http',
            }

**Comment by konradhalas** [comment]
Yep, it could be useful if you are using the same app to share your frontend and API, is it your case?

**Comment by LiteWait** [comment]
Yes, we've created a multi-tenant environment, configuration (like database
settings) are passed through uWsgi using environment variables.  Yet even a
given tenant may have more that one domain, so the email URL should reflect
the domain they are registering on.
