### ISSUE TITLE
FLAW: Authenticated user can view all other users at `/users` (not `/users/`)

### ISSUE THREAD

**Issue by sudomann** [sunscrapers/djoser#385]
I found this out using Postman. It does not matter what the request type is, I tried GET, POST, PUT, etc. and all the other 10 or so methods available in Postman.  I was using JWT authentication only. I provided `Authorization` in the header with my JWT `access` token. It returned an array of every single user.

**Comment by sudomann** [comment]
I'm not very experienced with Django. I temporally plugged this by setting `APPEND_SLASH = False` in settings.

It didn't prevent other paths like `/jwt/create` (instead of `/jwt/create/`) from working

**Comment by Pixsel1** [comment]
This bug was fixed in 1.6.0 version, that as authenticated user you can get all other users at `/users/` endpoint.
https://github.com/sunscrapers/djoser/pull/377
I can't reproduce this using `/user` url, I catch error `Page not found`.

Please update `djoser` to latest version and give me feedback.

**Comment by sudomann** [comment]
Okay the issue is gone in the new version as you've stated.
