### ISSUE TITLE
non_field_errors on password and username mismatch

### ISSUE THREAD

**Issue by Chadys** [sunscrapers/djoser#390]
For all of the retype serializers, the validation errors raised are non_field_errors ones. Should the base_endpoint documentation be updated or should this validation errors be raised on the 're_' field ? I can do the pull request depending on what is chosen.

**Comment by dekoza** [comment]
They should be raised on `re_*` field. In addition the key `non_field_errors`  should not be hardcoded as it depends on `settings.NON_FIELD_ERRORS_KEY`
