### ISSUE TITLE
AUTH_HEADER_TYPES configuration

### ISSUE THREAD

**Issue by Chadys** [sunscrapers/djoser#392]
I noticed this in the authentication_backend docs :

> Configure `django-rest-framework-simplejwt` to use the
> `Authorization: JWT <access_token>` header:
> 
>     SIMPLE_JWT = {
>        'AUTH_HEADER_TYPES': ('JWT',),
>     }

This make it seems like a needed configuration step, but in reality JWT authentication works correctly even without adding this settings, it just use the default `Bearer  ` authorization header as per the `django-rest-framework-simplejwt` documentation. This settings is completely independent from djoser and has no impact on its functionality so maybe this instruction should just be removed ?

**Comment by dekoza** [comment]
If this step can be ommited, the docs should be decluttered :wink:

**Comment by dekoza** [comment]
patch merged
