### ISSUE TITLE
Get instance of currently logged in user

### ISSUE THREAD

**Issue by tigranl** [sunscrapers/djoser#394]
It's seems like `login_user` doesn't actually register logged in user. I end up getting AnonymousUser, even after successful authorisation.

My views.py:
```
from rest_framework import routers
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from user_auth.models import User
from user_auth.serializers import UserSerializer


class PermissionViewSet(viewsets.ModelViewSet):

    queryset = User.objects.all()
    serializer_class = UserSerializer

    @action(detail=True, methods=['get'])
    def me(self, request):
        return Response({'r': request.user.username})


router = routers.DefaultRouter()
router.register(r'user', PermissionViewSet)

```

settings.py:
```
...
DJOSER = {
    'SERIALIZERS': {
        'user': 'user_auth.serializers.UserSerializer',
        'current_user': 'user_auth.serializers.UserSerializer',
    },
    'CREATE_SESSION_ON_LOGIN': True,
}
```

models.py:
```
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    db_table = 'auth_user'

    USER_GROUPS = (
        ('ADMIN', 'Admin'),
        ('MANAGER', 'Manager'),
        ('GAME_MASTER', 'Game master'),
    )
    username = models.CharField(max_length=20, unique=True)
    group = models.CharField(max_length=30, choices=USER_GROUPS)

    REQUIRED_FIELDS = ['email', 'group']
```
serializers.py:
```
from .models import User
from djoser.serializers import UserCreateSerializer


class UserSerializer(UserCreateSerializer):

    class Meta:
        model = User
        fields = ('username', 'group',)
```

**Comment by Pixsel1** [comment]
Hi @tigranl 
Can You give me more informations about this issue?
Steps to reproduce the problem will be cool

**Comment by tigranl** [comment]
Hi @Pixsel1
So I just simply follow the[ documentation](https://djoser.readthedocs.io/en/latest/sample_usage.html). After successful authorisation, when I access `~/user/me` it returns AnonymousUser, instead of actual User instance. 
```
Name: djangorestframework
Version: 3.9.4
Name: Django
Version: 2.2.1
Name: djoser
Version: 1.7.0
```

**Comment by dekoza** [comment]
Please provide 'console log' of your actions. Let us see step-by-step what you did and what was the output. I need to see you getting the token and then using it properly. This will help us to pinpoint what's wrong.

**Comment by tigranl** [comment]
@dekoza I retrieve the token:
`curl -X POST "http://127.0.0.1:8000/auth/token/login/" -H "accept: application/json" -H "Content-Type: application/json" -H "X-CSRFToken: Eeg1TlZdiFgRhaL0fe4H59Tows5sNCbZ3umw4LgpafXA374r45eDL9BxKME5oxMv" -d "{ \"password\": \"string123\", \"username\": \"test\"}"`
Output:
`{
  "auth_token": "fd03a9570cbc6558c4768a638553b6ecbd087c2a"
}`
Then once you get token token, as I can understand, login_user automatically registers it, using signals. But I still get AnonymousUser, when I try to access /user/me.

**Comment by dekoza** [comment]
1. You didn't provide the full log of accesing the `/me` endpoint.

2. No, the token is issued for you to use on each subsequent request you make - as per [documentation](https://djoser.readthedocs.io/en/latest/sample_usage.html) you should then make a request like this:

```$ curl -LX GET http://127.0.0.1:8088/auth/users/me/ -H 'Authorization: Token fd03a9570cbc6558c4768a638553b6ecbd087c2a'```

3. By the way: you don't need to send the CSRF token to log in.

**Comment by tigranl** [comment]
@dekoza but what's the point in `CREATE_SESSION_ON_LOGIN` then? /me endpoint just returns an empty string:
```
{
  "r": ""
}
```

**Comment by dekoza** [comment]
`CREATE_SESSION_ON_LOGIN` is usable only in browser which can handle the session cookie, should be used only for testing purposes (the docs need to be cleaned up, I admit) and will be removed (or at least depend on DEBUG setting). Please use the token as the documentation suggests and check the result.
