### ISSUE TITLE
Signal for logged in

### ISSUE THREAD

**Issue by deinega** [sunscrapers/djoser#402]
Does djoser provide a signal when user is logged in ?

There is a django.contrib.auth.signals.user_logged_in.
I am trying to use it while I am calling djoser 'token/login' endpoint. 
And it does not seem to be working:

```
from django.contrib.auth.signals import user_logged_in

def test(sender, user, request, **kwargs):
    print(request.user.is_authenticated)  # prints False while I am sending POST request to 'token/login' djoser endpoint with valid credentials

user_logged_in.connect(test)

```
How can I use it with djoser, or if I can use some djoser-specific signal?

**Comment by dekoza** [comment]
Logging in using Djoser sends Django's `user_logged_in` signal. Check [this fragment of our test suite](https://github.com/sunscrapers/djoser/blob/master/testproject/testapp/tests/test_token_create.py#L12) -- test method `test_post_should_login_user` specifically tests if this signal was sent.

**Comment by awwester** [comment]
For anyone else getting here, the signal is not sent when using `djoser.urls.jwt`, however that issue is in the [django-rest-framework-simplejwt](https://github.com/SimpleJWT/django-rest-framework-simplejwt/issues/190) sub-package

**Comment by cds88** [comment]
is it possible to use Djoser register signal with jwt auth ?

**Comment by Frikster** [comment]
jwt may not work but ordinary token auth certainly does work with the `user_logged_in` signal. I used the simple code below in `urls.py` to integrate with [django-fido](https://github.com/CZ-NIC/django-fido) for FIDO2 2FA.

```
def user_logged_in_receiver(sender, **kwargs):
    kwargs['request'].session[AUTHENTICATION_USER_SESSION_KEY] = kwargs['user'].pk


user_logged_in.connect(user_logged_in_receiver)
```
