### ISSUE TITLE
cannot import name 'list_route' from 'rest_framework.decorators'

### ISSUE THREAD

**Issue by alexseitsinger** [sunscrapers/djoser#405]
After an update, I receive the following error at runtime:

> cannot import name 'list_route' from 'rest_framework.decorators'

**Current Versions:**
- djoser==1.7.0
- djangorestframework==3.10.0

**Stack:**
1. djoser/urls/\_\_init\_\_.py:
     from .base import urlpatterns
2. djoser/urls/base.py:
    from djoser import views 
3. djoser/views.py:
    from rest_framework.decorators import list_route

You can see the deprecation notes [here](https://github.com/encode/django-rest-framework/pull/6687)
Thanks!

**Comment by hvdklauw** [comment]
See also: #370

**Comment by hvdklauw** [comment]
And #404

**Comment by luisroel91** [comment]
Is there a work around? This is app breaking :/

**Comment by Spriithy** [comment]
Got the same problem, but it is actually blocking when starting a new django rest / djoser project. Can't run the server at all... Any solution besides waiting ? Thanks in advance

**Comment by dekoza** [comment]
`djoser<2` is not compatible with drf>=3.10 - please freeze drf as `<3.10` for the time being, we're working on new `djoser` release.

**Comment by dekoza** [comment]
@Spriithy this week, stay tuned :smile:

**Comment by luisroel91** [comment]
If you need an immediate work around, fork this repo, patch the utils.py with the code provided in #404 and then use pipenv to install the patched code from your fork

That’s what I did temporarily . It’s been working so far.

**Comment by dekoza** [comment]
Djoser 2.0 released, I'm closing this. Note that djoser-2.0 is not fully compatible with djoser-1.x and DRF<3.10
