### ISSUE TITLE
/login username parameter isn't displayed by swagger-ui

### ISSUE THREAD

**Issue by stugots** [sunscrapers/djoser#41]
This involves multiple packages, and I'm not sure where the issue lies. I'll start here. :-)

Using...
- djoser from the git repository's master branch
- django-rest-swagger 0.2.9
- and the dist directory from swagger-ui's master branch..

I find that the "username" parameter for the /login endpoint isn't displayed in the swagger-ui documentation. "Password" is there, but username is not:

![screen shot 2015-04-29 at 11 30 42 am](https://cloud.githubusercontent.com/assets/231148/7398450/f483e4ba-ee63-11e4-9976-83e3bc42b29e.png)

In djoser.serializers.UserLoginSerializer.Meta.fields, "username" is not listed as a field. The username is manually picked off through User.USERNAME_FIELD, but Django Rest Swagger can't find that reference and so isn't aware of the username parameter.

**Comment by haxoza** [comment]
Thanks for submitting this issue. As far as I can see it's the same problem for `/username/` endpoint. What's more this issue proves that more people use swagger. Maybe we should officially support it.

**Comment by glothriel** [comment]
It's probably because username is not defined in serializer, as User.USERNAME_FIELD  is used instead, which is correct. I don't see easy solution to this.

**Comment by haxoza** [comment]
As far as I know after initial research some time ago there is an option to add doc strings that django-rest-swagger should be able to parse and generate appropriate JSON schema.

**Comment by jgirdner** [comment]
Any idea on when there might be a fix for this?

**Comment by piotr-szpetkowski** [comment]
![screenshot from 2017-10-03 12-47-31](https://user-images.githubusercontent.com/18597734/31121598-31d47366-a839-11e7-8669-8fa5abd4af9f.png)

DRF API docs correctly show the `username` parameter, so if the bug still shows up it's most probably on swagger side and there isn't much djoser can do here, therefore I'm going to close this issue, but if you believe that there is something more that I can do here, you are welcome to open a new issue.
