### ISSUE TITLE
user "delete" permissions and serializer settings not respected

### ISSUE THREAD

**Issue by gabriel-amram** [sunscrapers/djoser#417]
The permission_class setting for "user_delete" is not respected as `UserViewSet.get_permissions` doesn't check for action `delete` or (`me` with method `DELETE`). Instead, it just uses the default class permission.

Also the `UserViewSet.get_serializer_class` doesn't work for `user_delete` as the action that is checked is `remove` while the real action should be `delete`. This serializer setting is important as out-of-the-box it requires the user's password before deleting.

**Comment by dekoza** [comment]
Thank you for the report, I'll get to it asap.
