### ISSUE TITLE
Add support for django-rest-swagger

### ISSUE THREAD

**Issue by haxoza** [sunscrapers/djoser#43]
There are probably two things to do:
- add integration tests to testproject to check if the Swagger doc is generated without any issues
- fix the issue with dynamically added fields to serializers - see #41

**Comment by piotr-szpetkowski** [comment]
#41 is no longer an issue from what I can tell. Also I'm not really keen on idea of integration tests for a docs tool.

@haxoza can you elaborate if this issue is still valid?

**Comment by haxoza** [comment]
Looks like it is not valid any more. Especially if you already closed #41.

Let's just close this issue as well.

**Comment by piotr-szpetkowski** [comment]
Great. Thanks for the confirmation!
