### ISSUE TITLE
User activation logic does not follow docs

### ISSUE THREAD

**Issue by joshua-s** [sunscrapers/djoser#430]
According to [the docs](https://djoser.readthedocs.io/en/latest/settings.html#send-activation-email), a user is "required to click activation link sent in email" after updating their email.

This is not happening and further research into the code reveals this different logic:
https://github.com/sunscrapers/djoser/blob/c5a6f85efb55bc569529c45d98d3992f7ff7fc8b/djoser/views.py#L152

Could you please either patch this or update the docs?

**Comment by oma0256** [comment]
@dekoza since you've labeled this as a `bug` does this mean that this should be adjusted to match the `docs`, that is a user should receive an activation link when they update their email.

**Comment by oma0256** [comment]
@dekoza a follow up question say if `SEND_ACTIVATION_EMAIL` has been set to `True`. Does it mean if a `user` updates their `email` then they should be `deactivated` and `activated` once the click on the `activation link`.

**Comment by oma0256** [comment]
@joshua-s this seems to be working as expected with the docs. Is this still an issue?

**Comment by joshua-s** [comment]
@oma0256 sorry for the delay. Yes, this is still an issue because the email is only sent when the user is inactive and the user is not set to inactive when their email is updated.

**Comment by chico2k** [comment]
same issue for me. no activation email for the new email

**Comment by KaczuH** [comment]
After some investigation i've found the tests that already guards against such issue occuring.

https://github.com/sunscrapers/djoser/blob/de199e9997bb59cc0df09de8b09d0af40be408bb/testproject/testapp/tests/test_user_view.py#L45

Could you give more details on the problem?
