### ISSUE TITLE
Make init fails

### ISSUE THREAD

**Issue by ozeranskiy** [sunscrapers/djoser#437]
https://github.com/sunscrapers/djoser/blob/80769a342d10c39ef9c39423d12b53fd72bb7c97/Pipfile#L37-L42
What do these lines mean?

**Comment by oma0256** [comment]
@ozeranskiy What error do you get? I suspect it is related to `path` if so `path` should be pointing to the location of `djoser` on your local computer.

**Comment by ozeranskiy** [comment]
pipenv has an absolute path. It's not right.

**Comment by dekoza** [comment]
It looks like my private directory structure leaked :wink:

**Comment by ozeranskiy** [comment]
> It looks like my private directory structure leaked 😉

in my PR https://github.com/sunscrapers/djoser/pull/440/files#diff-1e61a31bf9b94805f869dc4137ec1885 i'm commented out this lines

**Comment by dekoza** [comment]
This need to be removed. And I'll probably remove those Pipenv* files if they are so leaky.

**Comment by ozeranskiy** [comment]
pipenv is used in the make init command. I think we should leave it, but clean it
