### ISSUE TITLE
I get 301 Moved Permanently

### ISSUE THREAD

**Issue by laesquinadelsofa** [sunscrapers/djoser#439]
when I try to make a request to /user/me  redirects me, even though the token passed.

**Comment by dekoza** [comment]
Where does it redirect?

**Comment by laesquinadelsofa** [comment]
the same endpoint. i'll want to send images to display the requests

**Comment by ozeranskiy** [comment]
add '/' to end url
see https://docs.djangoproject.com/en/dev/ref/settings/#append-slash
