### ISSUE TITLE
Registering users with the same email address more than once

### ISSUE THREAD

**Issue by oma0256** [sunscrapers/djoser#443]
I'm able to register more than one user using the same email address. I'm I missing something in my setup? If this is not the intended behaviour, I don't mind raising a PR to fix this.

**Comment by alextat120** [comment]
Do you have a custom user model? I think the default allows you to do that. If you have a custom one, you can set `unique=True` for the email field.

**Comment by ewelkaw** [comment]
According to documentation: https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#django.contrib.auth.models.User on field email there is (by default) no condition that it needs to be unique and if you will try it in your shell you will also find out that it is possible to create two users with the same emails but different usernames. As @alextat120 wrote above, if you need unique emails you should custom it.
