### ISSUE TITLE
`reverse('user-list')` doesn't work in tests?

### ISSUE THREAD

**Issue by ssrebelious** [sunscrapers/djoser#446]
I've bumped djoser version in my project from 1.3.1 to 2.0.3  and some tests involving user creation - `reverse('user-create')` url got broken. I peeked into the tests of the djoser test project and [it seems](https://github.com/sunscrapers/djoser/blob/master/testproject/testapp/tests/test_user_create.py#L25) that `reverse('user-list')` should be used instead. Unfortunately I keep getting this exception:

```
File ".venv/lib64/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-list' not found. 'user-list' is not a valid view function or pattern name.
```

In app itself POST to `/auth/users/` works as expected and users are created, which means that djoser has valid settings in the project. 

`reverse('jwt-create')` works.

How do I fix getting url for user creation via `reverse()` in tests?

**Comment by dekoza** [comment]
Please note that `djoser-2.0` broke backward compatibility. Now it uses ViewSets that have different path names etc. The last `djoser` version that supports your setup (and also provides viewsets for smooth transition) is 1.8. Please refer to the [documentation](https://djoser.readthedocs.io/en/latest/).

**Comment by ssrebelious** [comment]
> Now it uses ViewSets that have different path names etc.

@dekoza I got that, thanks. The aim of the question was find out which names should be used in `djoser-2.0`. I did study documentation and found nothing about the names for the `reverse()` function. I studied sources and especially tests in test-app and was unable to make `reverse()` accept some of the url names that were used in these tests, in particular: `user-list`. What am I doing wrong?

**Comment by shredding** [comment]
```
<URLPattern '^users/$' [name='user-list']>
<URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='user-list']>
<URLPattern '^users/activation/$' [name='user-activation']>
<URLPattern '^users/activation\.(?P<format>[a-z0-9]+)/?$' [name='user-activation']>
<URLPattern '^users/me/$' [name='user-me']>
<URLPattern '^users/me\.(?P<format>[a-z0-9]+)/?$' [name='user-me']>
<URLPattern '^users/resend_activation/$' [name='user-resend-activation']>
<URLPattern '^users/resend_activation\.(?P<format>[a-z0-9]+)/?$' [name='user-resend-activation']>
<URLPattern '^users/reset_password/$' [name='user-reset-password']>
<URLPattern '^users/reset_password\.(?P<format>[a-z0-9]+)/?$' [name='user-reset-password']>
<URLPattern '^users/reset_password_confirm/$' [name='user-reset-password-confirm']>
<URLPattern '^users/reset_password_confirm\.(?P<format>[a-z0-9]+)/?$' [name='user-reset-password-confirm']>
<URLPattern '^users/reset_username/$' [name='user-reset-username']>
<URLPattern '^users/reset_username\.(?P<format>[a-z0-9]+)/?$' [name='user-reset-username']>
<URLPattern '^users/reset_username_confirm/$' [name='user-reset-username-confirm']>
<URLPattern '^users/reset_username_confirm\.(?P<format>[a-z0-9]+)/?$' [name='user-reset-username-confirm']>
<URLPattern '^users/set_password/$' [name='user-set-password']>
<URLPattern '^users/set_password\.(?P<format>[a-z0-9]+)/?$' [name='user-set-password']>
<URLPattern '^users/set_username/$' [name='user-set-username']>
<URLPattern '^users/set_username\.(?P<format>[a-z0-9]+)/?$' [name='user-set-username']>
<URLPattern '^users/(?P<pk>[^/.]+)/$' [name='user-detail']>
<URLPattern '^users/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='user-detail']>
```

**Comment by joshjung** [comment]
Thanks, using `user-list` works to replace `user-create` during a Djoser upgrade.
