### ISSUE TITLE
TokenCreateSerializer does not honor custom AUTHENTICATION_BACKENDS

### ISSUE THREAD

**Issue by brandon-clair** [sunscrapers/djoser#458]
The [validation](https://github.com/sunscrapers/djoser/blob/master/djoser/serializers.py#L117-L121) of `TokenCreateSerializer` ignores any intentional return of `None` from `authenticate()`, and proceeds to lookup a User matching the parameters, instead. That means, if one were to supply their own custom authentication backend in Django's `AUTHENTICATION_BACKENDS` array, then any custom conditions that would prevent a user from being authenticated would not be honored.

Is this the intended behavior? If so, developers are expected to listen for a `user_login_failed`  signal, duplicate their custom backend conditions in a custom `token_create` `SERIALIZERS` override, or some smart third thing.

I would propose either removing the User lookup from `TokenCreateSerializer`, treating the case as "invalid credentials", or explicitly describing the behavior in the docs somewhere.

**Comment by ewelkaw** [comment]
@brandon-clair thank you for noticing this issue and first of all we will add info to `README` for other users and then probably we will try to redefine this part of `TokenCreateSerializer`.
