### ISSUE TITLE
doesn't  work  is_authenticated()  at the themplate

### ISSUE THREAD

**Issue by and07** [sunscrapers/djoser#46]
doesn't  work  is_authenticated() with 'rest_framework.authentication.TokenAuthentication' installed.
how to fix it?

**Comment by konradhalas** [comment]
Hi @and07! Could you provide more details about your problem?

**Comment by and07** [comment]
how to combine two methods of authorization that would after authorization and redirect to another page check written in the template worked

{% if user.is_authenticated %}
				<a href="#/logout/" class="js_logout" title="">logout</a>
....
....
{% endif %}

**Comment by and07** [comment]
thanks
