### ISSUE TITLE
compatibility with Django 3.0

### ISSUE THREAD

**Issue by vlavorini** [sunscrapers/djoser#465]
Hi,

   I tried the tests with tox with combinations including Django 3.0.
The only issues are when importing `django.utils.six`, which do not exist anymore in versions >3.0.
This happens in three files:

* testproject/testapp/tests/test_settings.py
* testproject/testapp/tests/social/test_provider_auth.py
* djoser/djoser/social/token/jwt.py

I am not an expert Python developer.

My workaround to allow the test execute is to select what to import based in the installed django version.

So, instead of:

    from django.utils import six

I wrote:

    import django
    if int(django.__version__.split('.')[0]) > 2:
        import six
    else:
        from django.utils import six
    del django

With this modification, the tests are succesful.

But, while this solution can be acceptable in the first two files, which are simply tests, I am not able to understand the consequences of this workaround in the third one (`djoser/djoser/social/token/jwt.py`).

Any comment appreciated.

**Comment by snmishra** [comment]
I made a PR #484 for this. Please see if it works.

**Comment by sanjioh** [comment]
Hi, it would be nice to have this landed, indeed :)
Is there something we (as community) can do to make it happen?
Thanks!
