### ISSUE TITLE
Issue with registration - "Unable to create account"

### ISSUE THREAD

**Issue by Gilberto97** [sunscrapers/djoser#475]
Hello! :) 
I have some issue with User registration. 
During creating new User from Postman i get "Unable to create account" response.
![image](https://user-images.githubusercontent.com/28743824/76302387-2c9dbf80-62c0-11ea-99b8-daa7c9c6257c.png)

In my terminal (docker) I get following informations:  

-  `ERROR:  null value in column "country_id" violates not-null constraint`
- `DETAIL:  Failing row contains (53, null, , t, jaroslawpsikuta1@gmail.com, pbkdf2_sha256$180000$p2Q8c4Du3uLF$o56YHGCS0ZutasVhevPXl8rrMG/VYL..., , null, , , , 2020-03-10 10:06:48.053201+00, null, f).`
- `STATEMENT:  INSERT INTO "accounts_user" ("last_login", "email", "is_superuser", "is_active", "password", "first_name", "last_name", "date_of_birth", "description", "address", "phone", "created_at", "country_id") VALUES (NULL, 'jaroslawpsikuta1@gmail.com', false, true, 'pbkdf2_sha256$180000$p2Q8c4Du3uLF$o56YHGCS0ZutasVhevPXl8rrMG/VYLiyzTB6LrSY4ws=', '', '', NULL, '', '', '', '2020-03-10T10:06:48.053201+00:00'::timestamptz, NULL) RETURNING "accounts_user"."id"`

It seems like Djoser don't see my request body, and it's trying to put empty or null values into database.
Till now, I tried following solution: 
https://stackoverflow.com/questions/49095424/customize-the-djoser-create-user-endpoint
...but it didn't work.

Do You have any ideas how to resolve it? Maybe I forgot something? Thank You for help :) 
Best regards,
Przemysław Baj

**Comment by Gilberto97** [comment]
Resolved: 
I needed to override User REQUIRED_FIELDS in model to make Djoser use it in serializer.

```
class User(AbstractUser):
    username_validator = None
    username = None
    ...

    USERNAME_FIELD = 'email' 
    REQUIRED_FIELDS = ['first_name', 'last_name', 'date_of_birth', 'address', 'phone', 'country']
```

**Comment by kev26** [comment]
Hi @prem-baj, I have the same your error in this post https://github.com/sunscrapers/djoser/issues/677, thank so much for any advice for me !
