### ISSUE TITLE
Is this repo is not maintained anyomore ?

### ISSUE THREAD

**Issue by mohmyo** [sunscrapers/djoser#476]

**Comment by YPCrumble** [comment]
I'd be happy to help with reviewing / merging PR's if maintainers need someone to help. I use this on production for two applications.

**Comment by dekoza** [comment]
@mohmyo This project is maintained on a "as time allows" basis, sorry.

@YPCrumble any reviews would be more than welcome, thanks.

**Comment by YPCrumble** [comment]
@dekoza thanks for your response - would it be OK for me to get permissions to merge PR's? I'd like to avoid doing the work and then having to wait for someone else to merge them.

**Comment by dekoza** [comment]
@YPCrumble I'm sorry but we don't plan to extend merge rights beyond members of @sunscrapers at the moment. That might change in future but we're not ready yet.

**Comment by YPCrumble** [comment]
@dekoza bumping this question - also related to #619 - I'm using djoser on a fairly large production site so would love to contribute more/merge PRs, but I don't want to contribute and have to wait forever for changes to be incorporated. 

I'd also be happy to take over the repo if that's of interest.

**Comment by dekoza** [comment]
@YPCrumble thanks for poking at me :smile: I'll get to that this or next week, promise.

**Comment by tartieret** [comment]
@dekoza also using this project in production and would like to help updating some of the dependencies (djangorestframework-simplejwt) for compliance reasons
Please let me know if there is anyway we can help, I can have resources allocated to this project

**Comment by YPCrumble** [comment]
@haxoza I'd still be willing to take over this repo if you're unable to spend time on it! It seems the test suite is still on TravisCI so isn't working anymore, and releases haven't been pushed in a while.
