### ISSUE TITLE
html email templates

### ISSUE THREAD

**Issue by mcgeeco** [sunscrapers/djoser#48]
Hi guys, really glad I found this app, it's helping me a lot. One of the reasons is how straight-forward it is to customise behaviour like this compared to the other apps, but have one question. I want to have html templates for activation/reset. Currently I'm overriding the activation view like this:
```python
class CustomRegistrationView(RegistrationView):
    """
    Override the Djoser view to provide an html template for activation email.
    """

    def get_send_email_extras(self):
        extras = super(CustomRegistrationView, self).get_send_email_extras()
        extras['html_body_template_name'] = 'activation_email_body.html'
        return extras
```
Is there an easier way of doing this? Would you guys consider looking for html templates by default or adding a config option for it? Cheers!

**Comment by haxoza** [comment]
Hi! I think you did it right according to the current code base. However as you suggested we should think how to make overriding email templates easier. Thanks for submitting this issue!

**Comment by andreyrusanov** [comment]
Probably create `subject_template_name` and `plain_body_template_name ` attributes and appropriate methods `get_subject_template_name` and `get_plain_body_template_name` will be a good idea - it will make customizing really flexible. And it is a really Django way to handle stuff like this in views

**Comment by andreyrusanov** [comment]
(I'm using your awesome library and I could not help answering on this) :smile:

**Comment by haxoza** [comment]
@mcgeeco & @andreyrusanov thanks for your comments and suggestions!

Please review my commit if you have a while :smiley:
