### ISSUE TITLE
AssertionError at /auth/logout

### ISSUE THREAD

**Issue by smcoll** [sunscrapers/djoser#5]
```
AssertionError at /auth/logout
'LogoutView' should either include a 'serializer_class' attribute, or use the 'model' attribute as a shortcut for automatically generating a serializer class.
```

i think this is due to a change in DRF.  Here are my versions:

```
Django==1.6.8
djoser==0.1.0
djangorestframework==2.4.4
```

Pull request with a fix incoming...

**Comment by haroldfredshort** [comment]
@konradhalas I get this same error, but only when attempting to GET the URL (DRF should give me a user-friendly description of the end point). Using POST to drive the logout works with no error. Applying [the proposed fix](https://github.com/smcoll/djoser/commit/f105b0f8a124cf803d49f23c1f5249ff8c12f0e5) from @smcoll fixes the GET request for me.

My versions:
```
Django==1.7.6
djangorestframework==3.0.5
djoser==0.2.1
```
