### ISSUE TITLE
Enable DRF token based auth (customer request)

### ISSUE THREAD

**Issue by urijah** [sunscrapers/djoser#503]
![image](https://user-images.githubusercontent.com/2709312/84234057-3ab1d680-aa8f-11ea-8f22-1139a995af65.png)

Simple token,? JWT (https://github.com/TriplePoint-Software/hoaas/pull/1072 note)? https://www.django-rest-framework.org/api-guide/authentication/#third-party-packages ?

**Comment by tomwojcik** [comment]
That's literally what Djoser provides. I don't understand your question. Also, posting someone's PII without their will might not be the best idea.

Please go through our documentation to learn more. https://djoser.readthedocs.io/en/latest/getting_started.html
