### ISSUE TITLE
Why only users with usable passwords can use password reset routine?

### ISSUE THREAD

**Issue by barszczmm** [sunscrapers/djoser#51]
In this line: https://github.com/sunscrapers/djoser/blob/master/djoser/views.py#L125 there is a check if user has unusable password and such user is ignored when generating password reset email for him. What's the reason for that?

**Comment by konradhalas** [comment]
Default Django policy "prevent inactive users and users with unusable passwords from resetting their password" (check https://github.com/django/django/blob/master/django/contrib/auth/forms.py#L213). It makes sense for me.

Do you have any issue with such behaviour?

**Comment by barszczmm** [comment]
I need other behaviour in one of my project, but that's not an issue, I can handle it other way. Just wanted to know why it is done like that and if that's default Django policy then I'm OK with that. It should be left as it is IMO. 

Thanks for fast response.
