### ISSUE TITLE
SendGrid integration

### ISSUE THREAD

**Issue by ahmadshaik1106** [sunscrapers/djoser#510]
I am unable to send mails in production, how can I integrate djoser with SendGrid? 
I am using heroku for hosting.
Thanks!

**Comment by tomwojcik** [comment]
It's rather a Django or Sendgrid question, not Djoser.

We are using Django configuration for sending emails.

There's also a [guide](https://sendgrid.com/docs/for-developers/sending-email/django/) for integrating these two.

```
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey' # this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
EMAIL_PORT = 587
EMAIL_USE_TLS = True
```

After that everything should work out of the box.
