### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fmarco** [sunscrapers/djoser#512]
Hello,

do you have some plans about a new release (official django 3.0 supports etc.)?

**Comment by warmwaffles** [comment]
I would also like to know if there is planned support for 3.0

**Comment by tomwojcik** [comment]
Please check the latest release [`2.0.5`.](https://pypi.org/project/djoser/2.0.5/) That's where official support for Django 3.x has been added. 

Worth noting, the previous version was also working fine, now I just added some tests for Django 3 and resolved Django 4 warnings.
