### ISSUE TITLE
Djoser + reCaptcha?

### ISSUE THREAD

**Issue by kszmigiel** [sunscrapers/djoser#514]
Hello guys!

First, I love your lib, it's a pleasure to use it for JWT auth in DRF ❤️ 
Second, the project I'm working on currently is requiring me to implement reCaptcha (v3) during user registration, instead of sending activation email. I'm trying to figure it out by myself, but it's not going well. Any tips?

Thanks in advance,
Kacper

**Comment by dekoza** [comment]
This looks like a good Feture Request :slightly_smiling_face: Probably the best way right now is to use [drf-recaptcha](https://pypi.org/project/drf-recaptcha/). This will most probably require you to write your own serializer for the JWT view and in the process - use your own JWT views. Djoser's JWT support means that we only pass urls to `simplejwt` views.

Hope that helps!

**Comment by dekoza** [comment]
Another way would be to write your own middleware that catches the POST request, processes reCaptcha and then...

**Comment by kszmigiel** [comment]
@dekoza Thank you for your answer! I think I'll proceed with writing middleware just not to mess with customization of views which play a key role. As you noticed, it would make a great feature to djoser too 😄

**Comment by tomwojcik** [comment]
Closing for now as I think there's nothing more to be added.
