### ISSUE TITLE
Is there a way to customize djoser url

### ISSUE THREAD

**Issue by ashiljacob** [sunscrapers/djoser#518]
My question is that is there any way to customize the djoser url. Like i want to use `users/profile` instead of `users/me`

**Comment by tomwojcik** [comment]
I think a quick solution is to overwrite `me` action and basically replace the default url using `url_path` parameter.
That way internally the action is still `me`, which is important for determining serializer and permission.

```
    @action(["get", "put", "patch", "delete"], detail=False, url_path='profile')
    def me(self, request, *args, **kwargs):
        return super().me(request, *args, **kwargs)
```

Even though it'd be rather easy to allow a customization of this resource using settings, I don't think it's a good idea to allow it as `users/me` is a popular convention for REST API and `users/<anything else>` sounds like another resource.
