### ISSUE TITLE
Known IPs verification at authentication

### ISSUE THREAD

**Issue by johnnfujita** [sunscrapers/djoser#519]
Due to the abstraction level that djoser provides, i am not sure at what layer it plugs to the auth backend. So i was affraid to add a custom ip check, email confirmation for unknown ip access and saving the new ips, and ending up inserting some insecurity. So basically i would like anyone to either point out some that already done it, or just show me what function does djoser call for authentication so i can properly overwrite it, with the new functionality added. Thanks!

**Comment by tomwojcik** [comment]
I'm a bit lost at what exactly it is that you are asking about.  Do you want to prevent some IPs from accessing your API? Do you want to notify the user he was logged in from a new IP?

**Comment by johnnfujita** [comment]
It was a feature to warn users about suspicious login attempts. But i have managed to work it out...i can't quite remember right now, but i think i did overwrite  the create, or perform_create function from the class. It worked out nicely. Thanks
