### ISSUE TITLE
Feedback and questions

### ISSUE THREAD

**Issue by saritasa** [sunscrapers/djoser#52]
hi Guys,

I do like the product. 

The following is the feedback and questions:

**/password/reset**

If you provide invalid email it does return you 200 HTTP code and doesn't tell you that email is not found in the database. I'd like to get a different response back, such as 404 with "details": "such email doesn't exists"

**How to integrate with custom model inherited from django.contrib.auth.user model?**

Would be awesome if small tutorial is provided

**Update profile - 3 methods?**

What's the motivation to make a 3 different methods to update profile /me and POST /username, POST /password? I think it's nicer to just call PUT /me method to update username, password. Otherwise a client should hit 3 different API endpoints. 

**How to update other fields of profile with PUT /me?**

It seems right now it only updates email field and nothing else. What about first_name, last_name? What about other custom fields of the model (question #2 above)?

**HTTP Error codes (404, 422)**

For example when you do POST /login with non-existing username you get this

```
400
{
  "non_field_errors": [
    "Unable to login with provided credentials."
  ]
}
```
but it's correct request, while the response says: 400 (Bad Request). It would be nicer to have 404, error.

Also when you do  POST /register and provide non-unique username you get this:

```
400
{
  "username": [
    "This field must be unique."
  ]
}
```
however this is a business logic error and code 422 is better for such use case

**Generic message**

If I do POST /username and provide incorrect value of current_password I get this:

```
400
{
  "current_password": [
    "Invalid password."
  ]
}
```

Which makes it hard for the client (say Android mobile app) as I need to know and define maps ahead of time.

Would not it better to return something like this:

```
422
{
  "errors": 
      [
           {"field": "password", "message""Invalid password provided"},
           ....
     ]
}
```
the same would be for registration and other methods. That way I don't need to define the model for each JSON response body, as they're all generic. Otherwise for each API call you have to create a custom parser (and you have to know all the fields ahead of time). 

**Validation for Incorrect request**

If I do:
*PUT /me*
```
{
    "email": "admin@admin.com",
    "eeee": "jim",
    "zzz": "smith"
}
```

I'll get 200 HTTP code back:

```
{
  "email": "admin@admin.com",
  "id": 1,
  "username": "admin"
}
```
However the example above submitted 2 random fields. I would value if API return something like this:

```
422 or 400
{
  "errors": 
      [
           {"field": "eee", "message""Unknown field"},
           {"field": "zzz", "message""Unknown field"},
           ....
     ]
}
```

**Comment by mcgeeco** [comment]
I agree with the password reset thing. I've had to override every auth package I've come across to give a 'Email not registered' error back instead. I believe (but I could be wrong) that there are security concerns regarding this. ie - that if you don't want to reveal whether or not an email is registered with the site.

**Comment by konradhalas** [comment]
Hi @saritasa, thank you for your feedback. We'll have Djoser sprint in upcoming week, so we will definitely consider all your issues. 

For now I'll just say that in most cases we're trying to follow with solutions implemented in Django and Django Rest Framework by default. E.g. I don't think it's a good idea to reimplement Django Rest Framework error handling (http 400, with simple dict of errors as response) or Django password reset policy (Django do not check if email exists or not in database).

**Comment by konradhalas** [comment]
Hi @saritasa! Once again, thank you for your feedback. Please find my answers below.

> /password/reset

> If you provide invalid email it does return you 200 HTTP code and doesn't tell you that email is not found in the database. I'd like to get a different response back, such as 404 with "details": "such email doesn't exists"

As I said in my previous answer - in most cases we are trying to follow default Django polices. If you are using `django.contrib.auth.views.reset_password` and the email address provided does not exist in the system, this view won’t send an email, but the user won’t receive any error message either. Why we should change that?

> How to integrate with custom model inherited from django.contrib.auth.user model?

> Would be awesome if small tutorial is provided

Could you provide more information which part of integration is problematic? If you follow Django documentation about user customization, Djoser should work out of the box.

> Update profile - 3 methods?

> What's the motivation to make a 3 different methods to update profile /me and POST /username, POST /password? I think it's nicer to just call PUT /me method to update username, password. Otherwise a client should hit 3 different API endpoints.

To change user password or username you have to provide current password. When you are using `/me` endpoint you don't have to. It's a common solution and in Djoser we follow this way.

> How to update other fields of profile with PUT /me?

> It seems right now it only updates email field and nothing else. What about first_name, last_name? What about other custom fields of the model (question #2 above)?

If you want to add "non-base" fields to `/me` endpoint you should extend `User.REQUIRED_FIELDS`.

> HTTP Error codes (404, 422) ...

I don't think it's a good idea. By default, DRF is returning 400 when validation failed. 404 should be reserved only when sth is missing - it's a definitely not a case when user provide wrong credentials.

> Generic message

and 

> Validation for Incorrect request

Once again, it's a way how DRF handle requests by default - we should leave it as it is.

**Comment by segunemma2003** [comment]
> I agree with the password reset thing. I've had to override every auth package I've come across to give a 'Email not registered' error back instead. I believe (but I could be wrong) that there are security concerns regarding this. ie - that if you don't want to reveal whether or not an email is registered with the site.

pls can you explain how you do it?
