### ISSUE TITLE
Specify sender email address for emails

### ISSUE THREAD

**Issue by ronaldchoi** [sunscrapers/djoser#520]
Apologies if this has been asked but I could't found it in existing issues.

Is there anyway I can configure the sender email address of account activation email or other general emails (e.g. password reset)?

**Comment by pickyuptruck** [comment]
add 
`DEFAULT_FROM_EMAIL = "email@example.com"
`
to your settings file

**Comment by tomwojcik** [comment]
Hey @ronaldchoi , 

What @pickyuptruck said is true. In djoser we use our own mail templating lib [`django-templated-mail`](https://github.com/sunscrapers/django-templated-mail) which is a django mailing system with some small changes we wanted.

If you send an email, [`DEFAULT_FROM_EMAIL`](https://docs.djangoproject.com/en/3.1/ref/settings/#default-from-email) from settings is used.

If you passed a `from_email` to the `send` method of the email object, it will be used instead.
 
https://github.com/sunscrapers/django-templated-mail/blob/65e5a34f69d50d4d1b6acdd337f9efcc44b32fae/templated_mail/mail.py#L69-L80
