### ISSUE TITLE
Get "is_staff" attribute with users/me/ endpoint

### ISSUE THREAD

**Issue by juliuszsielski** [sunscrapers/djoser#521]
Is it possible to get "is_staff" attribute with auth/users/me/ endpoint?

EDIT:
Here is a solution:

settings.py
```
DJOSER = {
    'SERIALIZERS': {
        'current_user': 'api.serializers.CurrentUserSerializer',
    },
}
```
views.py
```
class CurrentUserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = CurrentUserSerializer
```

serializers.py
```
class CurrentUserSerializer(ModelSerializer):
    class Meta:
        model = User
        fields = ('username', 'email', 'is_staff')
```

**Comment by FedericoCapaldo** [comment]
Thanks for sharing your solution for this problem. why did you have a CurrentUserViewSet in views.py? the endpoint users/me in Djoser was overridden fine just with the update in settings.py
