### ISSUE TITLE
loading current user data

### ISSUE THREAD

**Issue by olivernashivy** [sunscrapers/djoser#561]
i am working on an api and all urls work except users/me/ . i can loggin with postman and get access token but if i try to login with that token to get current user, it tell me authentication credentials fail. am i doing it wrong? what else do i neeed to send in 
to get the current user data.
![AUTH](https://user-images.githubusercontent.com/75489794/101180730-9c28bb80-3654-11eb-8138-aae47245a258.PNG)
in my setting.py 
`REST_FRAMEWORK = {
       
         'DEFAULT_AUTHENTICATION_CLASSSES':(
           'rest_framework_simplejwt.authentication.JWTAuthentication',
         ),
   
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME':timedelta(days=2),

  
}`
At one time the code was working but it stop and i searched wondering whats the problem.

**Comment by malikfaiq** [comment]
I think you are missing JWT before token.
![tokenissuejoser](https://user-images.githubusercontent.com/10773864/101470840-59265b00-3968-11eb-835c-229c015e98bf.png)

**Comment by saeedblanchette** [comment]
It working for me.  look at these possibilities 
Part of the token is missing.
You didn't include the  Bearer keyword on the authorization header request.  go to the authorization tab in postman select Bearer Token an insert  the access token value

**Comment by olivernashivy** [comment]
I did that but the problem remain. Just looking to your token I notice it's small than mine mine is like 2,3 times longer. Am I sending the wrong token. After auth/jwt/create/ I select the access and send it.

**Comment by malikfaiq** [comment]
@olivernashivy  it's not the full token in my picture. I had update simple JWT settings ```
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',), }
```

That's why I have added JWT in front of my token, you have not changed the settings so you have to add Bearer in front of your token in postman.

**Comment by haxoza** [comment]
It seems that @saeedblanchette and @malikfaiq solved the requested issue, which in fact is not djoser's issue. It's more about simplejwt package configuration. That's why I'm closing this issue.
