### ISSUE TITLE
Unauthorized: /auth/jwt/create/

### ISSUE THREAD

**Issue by epetrov1** [sunscrapers/djoser#567]
I install Djoser with JWT. I am able to activate the user with the Postman. When I send a POST request to this url: /auth/jwt/create/ I get this message from postman:  "detail": "No active account found with the given credentials".

**Comment by malikfaiq** [comment]
Did you verified the username and password you are providing while making the request?

**Comment by epetrov1** [comment]
https://stackoverflow.com/questions/65156272/i-am-creating-a-django-api-for-the-purpose-of-authentication-i-implemented-dj 
This is my code...

**Comment by malikfaiq** [comment]
code is looking fine. Can you share the screenshot of accessing API using Postman?

**Comment by epetrov1** [comment]
Yes, I send this body and I get Postman response: "No active user with given credentials"

**Comment by malikfaiq** [comment]
Did you activate the account before accessing this endpoint?
![image](https://user-images.githubusercontent.com/10773864/102982386-409f6e80-452c-11eb-838b-a09da47a0752.png)

**Comment by epetrov1** [comment]
Yes, I did it. I received an email: an account is activated and ready to use. I checked the database. The record is existing.

**Comment by malikfaiq** [comment]
The last resort is to check the username and password you might have missed something. Are you providing email as a username?

**Comment by epetrov1** [comment]
![image](https://user-images.githubusercontent.com/53528561/102983168-54d77180-4514-11eb-89d5-1d3a4d26e879.png)

**Comment by mashahabi15** [comment]
> Yes, I did it. I received an email: an account is activated and ready to use. I checked the database. The record is existing.

Hello. "is_active" field is 1 in the database record?

**Comment by epetrov1** [comment]
Yes.

**Comment by haxoza** [comment]
I'm closing the issue as it is not djoser related problem.

btw, @epetrov1 I answered your question on stackoverflow.
