### ISSUE TITLE
ImportError: No module named authtoken

### ISSUE THREAD

**Issue by mcastle** [sunscrapers/djoser#59]
When I try to use `url(r'^auth/', include('djoser.urls.authtoken')),`, I get the error `ImportError: No module named authtoken`. This is with djoser 0.3.1, djangorestframework 3.1.3 and Django 1.8.3.

**Comment by mcastle** [comment]
Nevermind. I see the docs for version 0.3.1 are correct.

**Comment by haxoza** [comment]
Yup, currently we're in the process of decoupling DRF auth token app.
