### ISSUE TITLE
Some url names clash with default Django url names.

### ISSUE THREAD

**Issue by mcastle** [sunscrapers/djoser#60]
For instance, login and logout clash with standard Django registration urls.

**Comment by haxoza** [comment]
True, thanks! We didn't noticed that because we mainly deployed pure REST django apps with djoser.

**Comment by konradhalas** [comment]
@haxoza we had offline discussion about this some time ago - can you remember me your thoughts?

**Comment by mmarksnippety** [comment]
I make pull request #129. It introduces configurable URL namespace. We plan to merge it in this week
