### ISSUE TITLE
No module named authtoken

### ISSUE THREAD

**Issue by eltronix** [sunscrapers/djoser#62]
After following the installation instructions for Token Based Authentication I keep getting the above error. I'm using django 1.8.3 and DRF 3.1.3.

Is it possible that the version on pip is different from the one on Github?

**Comment by rashidalnaemi** [comment]
Same here.

The problem is from  urls.py 'djoser.urls.authtoken'

**Comment by haxoza** [comment]
@eltronix @rashidalnaemi thanks for checking out djoser!

Currently we're actively working on new release so the readme file with the documentation goes beyond the latest version from pip. Please check out [latest releases](https://github.com/sunscrapers/djoser/releases) to browse documentation for given version from pip.

Btw, here is a progress for 0.4.0 release: https://github.com/sunscrapers/djoser/milestones
