### ISSUE TITLE
Move documentation to Read the Docs

### ISSUE THREAD

**Issue by haxoza** [sunscrapers/djoser#63]

**Comment by dunmaksim** [comment]
+1

**Comment by konradhalas** [comment]
Are we sure about this? Now everything is in the one place. Do we have enough docs to move our README to RTD?

**Comment by konradhalas** [comment]
I will answer myself: because on RTD it's easier to browse different versions of documentation (e.g. development vs latests stable release). Currently many people are confused about differences between PyPI version and Github.

So I'm +1.

**Comment by piotr-szpetkowski** [comment]
Done.
