### ISSUE TITLE
Return login user data in login call

### ISSUE THREAD

**Issue by s2krish** [sunscrapers/djoser#64]
Hay Guys,

Currently login function returns toke on successful authentication which is very nice. 

From the practical prospective, wouldn't it be nice to return user data? For example in a real app there's many API calls which uses user Id. But to get user user Id, another get request to /me has to be made. If login function returns user data + tokens , one request can be avoided.

Thanks

**Comment by haxoza** [comment]
Sure, good idea. We will think about that.

**Comment by alican** [comment]
Will it be available in the next version?

**Comment by konradhalas** [comment]
Hi @s2krish thank you for your feedback and sorry that you have to wait so long.

We decided that each endpoint should be independent and should have only single responsibility. I understand that from the client point of view, it will be easier to receive user data after login in 99% cases, but for a purity reasons we are not doing it. This is why we also removed `LOGIN_AFTER_REGISTRATION` and `LOGIN_AFTER_ACTIVATION` flags (#57). Please check also #56.

As always, this is a trade off, but I hope our thinking is ok in this matter.

**Comment by hammadzz** [comment]
This is such a common case. Is there any documentation how to be able to implement these easily? I also want to have login after registration functionality. This is probably what most people want to do, there should be documentation how to easily add such functionality.

**Comment by nitrag** [comment]
Purity < User Experience.
