### ISSUE TITLE
Login with token

### ISSUE THREAD

**Issue by sylflo** [sunscrapers/djoser#65]
I'm trying to use djoser with Token Based Authentication.

I can register no problem for this.
But when I want to login I got the token but I don't know what to do next.

I followed the instructions for the Customizing authentication backend.

I use this ```{% if user.is_authenticated %}``` to see if the user is connected. But apparently my user is not connected after getting the token.

**Comment by haxoza** [comment]
Thanks for trying djoser!

As far as I see you are mixing two concepts. You got the token which is designed to support REST authentication but then you probably use just normal django views and templates.

If you want to be sure that token is used properly then:

* get the token via login endpoint
* set the http [auth header](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) to each next following request (let's say ajax request)
* ensure that you set django rest framework authentication backend to [TokenAuthentication class](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)
* ensure that your django view inherits from [APIView class](http://www.django-rest-framework.org/api-guide/views/#class-based-views) from django rest framerwork.
