### ISSUE TITLE
Return password incorrect error message for login

### ISSUE THREAD

**Issue by jinpark** [sunscrapers/djoser#66]
Currently the login view returns the general `invalid_credentials` error message if either the username or password is incorrect. It would be nice to know if they had an incorrect password only or if their username was wrong

**Comment by haxoza** [comment]
Actually that could be a nice feature for improving UX. However we use `[authenticate](https://github.com/django/django/blob/master/django/contrib/auth/__init__.py#L62)` function from `django.contrib.auth` to authenticate user and it does not say which piece of credentials is wrong. I think that this behaviour is determined by security reasons.

What's more I'm not sure if this is the feature request to Djoser or to Django itself. Any idea how to do it?

**Comment by jinpark** [comment]
I thought about this more and while it is doable by overriding the django authenticate function in djoser, I feel like this would be a security mistake as you've mentioned. I'll close this for now since it doesn't make sense for this functionality to be in djoser.

Sorry!
