### ISSUE TITLE
Missing Release notes for 2.1.0

### ISSUE THREAD

**Issue by gagantrivedi** [sunscrapers/djoser#669]
It looks like we are using https://github.com/sunscrapers/djoser/blob/master/CHANGELOG.rst for keeping release notes/change log 
but It looks like that it's missing changelog for `2.1.0` is there reason why that's the case? Have we moved the changelog to somewhere else?
PS: Thank you for the awesome work that you guys are doing.

**Comment by jaap3** [comment]
Release notes for 2.1.0 have been added at some point

https://github.com/sunscrapers/djoser/blob/master/CHANGELOG.rst#210-2020-10-30
