### ISSUE TITLE
Djoser not compatible with social-auth-app-django=5.0.0

### ISSUE THREAD

**Issue by zelhus-iliyas** [sunscrapers/djoser#694]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
djoser 2.1.0 requires social-auth-app-django<5.0.0,>=4.0.0, but you have social-auth-app-django 5.0.0 which is incompatible.

I was trying to install new version of social-auth-app-django 5.0.0 .

**Comment by zelhus-iliyas** [comment]
@sunscrapers could you please solve this?I should deploy in production ..

**Comment by code-formel** [comment]
Hi @sinisarudan, @zelhus-iliyas 

Use` git+https://github.com/sunscrapers/djoser@master#egg=djoser`  instead of `djoser==2.1.0`  in your requirements.txt. 
you will have the latest updates.

**Comment by bj00rn** [comment]
https://github.com/sunscrapers/djoser/issues/668

**Comment by tomwojcik** [comment]
@zelhus-iliyas Djoser 2.2.0 has been released 2 weeks ago. It supports social-auth-app-django >5. Feel free to reopen if you run into issues.
