### ISSUE TITLE
Add Blacklist endpoint for jwt endpoints

### ISSUE THREAD

**Issue by cooldragon12** [sunscrapers/djoser#712]
Please update the rest_framework_simplejwt package to v5.*  so we could add blacklisting of token upon logout using jwt

**Comment by artursniegowski** [comment]
Not sure if this helps, but can install the latest version than it works fine.
#694
> Use` git+https://github.com/sunscrapers/djoser@master#egg=djoser` instead of `djoser==2.1.0` in your requirements.txt. you will have the latest updates.

**Comment by tomwojcik** [comment]
@cooldragon12  Djoser 2.2.0 has been released 2 weeks ago. It should work fine with the latest rest_framework_simplejwt. Feel free to reopen if you run into any issues.
