### ISSUE TITLE
install doesn't include `urls` module

### ISSUE THREAD

**Issue by smcoll** [sunscrapers/djoser#75]
i pip installed the master branch:

`$ pip install git+git://github.com/sunscrapers/djoser.git --upgrade`

But at the auth root view i get `No module named urls`.

The installed directory looks like this:

```
/templates
__init__
constants
serializers
settings
signals
utils
views
```

The `urls` module was not installed.  Does it need to be listed in MANIFEST.in?

**Comment by jschneier** [comment]
I think instead you need to add `djoser.urls` to the packages setting in setup.py
