### ISSUE TITLE
Moving @actions in to separate mixins

### ISSUE THREAD

**Issue by GrbavaCigla** [sunscrapers/djoser#769]
Hello, I would like to propose a few changes in the implementation of `UserViewSet`.

**What am I proposing?**
Make a class that inherits `ModelViewSet` and has basic `get_queryset`, `get_permissions`, `get_serializer_class` and so on...
Move actions to separate mixins and make `UserViewSet` inherit all those mixins and base class.
For methods like `get_permissions` that do stuff like this:
```py
if self.action == "create":
    self.permission_classes = settings.PERMISSIONS.user_create
elif self.action == "activation":
    self.permission_classes = settings.PERMISSIONS.activation
elif self.action == "resend_activation":
    self.permission_classes = settings.PERMISSIONS.password_reset
...
```
we could just add dictionary to base class.

**Why are these changes necessary?**
To better comply with django standards and make `UserViewSet` fully customizable. With these changes you will be able to completely change `/users/` endpoints without effort.

I would like to hear your feedback on this, what should I change and should I do it?

**EDIT**: Just saw #549, my proposal is a little bit different, but we solve the same problem.

**Comment by tomwojcik** [comment]
I agree, allowing for a more granular configuration would make sense. Though a different approach is planned. Please share your thoughts here. 

https://github.com/sunscrapers/djoser/discussions/777
