### ISSUE TITLE
request.DATA` has been deprecated

### ISSUE THREAD

**Issue by grebenshchikov** [sunscrapers/djoser#77]
NotImplementedError at /api/password/reset/
`request.DATA` has been deprecated in favor of `request.data` since version 3.0, and has been fully removed as of version 3.2.

Need change request.DATA to request.data style

**Comment by jamiecounsell** [comment]
Fixed here: 24eb136c47f7f39b1cd83533ba089af39af3ef84
Would love to see an update in PyPI!

**Comment by haxoza** [comment]
It was already fixed in the master branch for 0.4.0 version but now it's also fixed for 0.3 version in separate branch.

**Comment by jamiecounsell** [comment]
@haxoza has the PyPi package been updated? 0.4.0 is fine but I was only able to get 0.3 from PyPi.

**Comment by haxoza** [comment]
I've just uploaded 0.4.0 to PyPi.

**Comment by jamiecounsell** [comment]
Awesome!
