### ISSUE TITLE
Disable sending email for activation

### ISSUE THREAD

**Issue by Ishogbon** [sunscrapers/djoser#770]
I don't want to use Djoser's URL Activation scheme, I much prefer the OTP Activation. Since Djoser doesn't offer an OTP alternative, I created my own OTP activation system. Is there a way I can prevent Djoser from sending the URL activation emails, Or is it something that needs to be worked on

**Comment by tomwojcik** [comment]
Did you try

```
DJOSER = {
    'SEND_ACTIVATION_EMAIL': False,
}
```
?

Feel free to reopen if it doesn't work.
