### ISSUE TITLE
Implement urls domain, protocol and site name for frontend 

### ISSUE THREAD

**Issue by FraCata00** [sunscrapers/djoser#781]
If you're develop a backend and frontend in separate projects, cannot add `ACTIVATION_URL` in DJOSER settings like this
```python
DJOSER = {
    "SEND_ACTIVATION_EMAIL": True,
    "SEND_CONFIRMATION_EMAIL": True,
    "USER_CREATE_PASSWORD_RETYPE": True,
    # specially this
    "ACTIVATION_URL": os.environ.get(
        "DJANGO_ACTIVATION_URL", "auth/users/activate/{uid}/{token}"
    ),
}
```
because implicitly check inside the backend this path from example `localhost:8000`, and maybe the frontend project is in another repo and another host

From documentation:
![image](https://github.com/sunscrapers/djoser/assets/78490028/dbe86144-c657-42af-b78a-0a06785fb1b0)

This PR #729 by @n-borges allows this functionality
Please check this out ❤️

**Comment by RodrigoSosa95** [comment]
Are there any plans to integrate this into the project? I have this exact use case

**Comment by RodrigoSosa95** [comment]
For anyone trying to get this result take a look at [this stackoverflow question](https://stackoverflow.com/a/71696230)

Adding `DOMAIN` and `SITE_NAME` solves it.

**Comment by tomwojcik** [comment]
Sorry it took so long, merged. I will release it within a month with other minor improvements. Thanks!
