### ISSUE TITLE
VK Oauth2 doesn't work from Djoser Social

### ISSUE THREAD

**Issue by va1ngvarr** [sunscrapers/djoser#788]
Hello everyone who sees my issue. So, I'm trying to implement **VK** authorization, but it doesn't work. However, I'm doing what I should do according to the documentation and it works well for **Mailru** authorization!

First of all, my oauth enpoint is located at `/api/auth/o/`. So, I send GET-request to the endpoint+provider_name. In my case that's _mailru_ (what doesn't matter now as it's alright) and _vk-oauth2_. Also, I need to pass redirect_uri. It causes that I get link which I'd send to user. So I pass it. At redirect_uri I passed I get in query parameters values _state_, _redirect_state_ (only for vk, but there's no this thing in the djoser documentation) and _code_.

Then I should send request to the same endpoint, but using POST-method and pass the data I've got (state, code). Then It's supposed to respond me with access token what it does with mailru oauth, but does not with vk

**I get the following error from djoser:**
```
{
    "non_field_errors":  [
        "Your credentials aren't allowed"
    ]
}
```

**P.S.**
Here's the documentation https://djoser.readthedocs.io/en/latest/social_endpoints.html

**Comment by tomwojcik** [comment]
Djoser is using https://github.com/python-social-auth/social-app-django . If VK specifically doesn't work, it's probably that the configuration is incorrect or there's a bug in this library. Either way, Djoser is just forwarding the message returned from social app. Consider opening a ticket there.
