### ISSUE TITLE
"Authentication credentials were not provided" on log out TokenAuthentication

### ISSUE THREAD

**Issue by engin-can** [sunscrapers/djoser#802]
Hi,

I keep getting the following error when I log out with `TokenAuthentication`:  `Authentication credentials were not provided.`.
Any idea why this is happening?

`curl -X POST http://localhost:8000/auth/token/logout/  --data 'f4c30aed2268e8d952a742e82fe24b012766fe5f' -H 'Authorization: Token f4c30aed2268e8d952a742e82fe24b012766fe5f'`

**Comment by williank** [comment]
Worked...
'AUTH_HEADER_TYPES': ('JWT', 'Bearer'),

The djoser needs this key in the settings.SIMPLE_JWT

Simplejwt itself doesn't depend on it.
