### ISSUE TITLE
How to return error code 403 instead of 400 when user hasn't been activated?

### ISSUE THREAD

**Issue by engin-can** [sunscrapers/djoser#805]
Hi, I have a `ModelBackend` to check if user has been activated. I want it to return `PermissionDenied` but it returns error code `400` with `{"non_field_errors":["Unable to log in with provided credentials."]}` as error. I want error code `403` with `{"non_field_errors":["Your account requires activation."]}` instead. 

This works by raising `ValidationError`, but this returns `400` instead of `403`.  Any idea how I can solve this?

```
class TokenCreateModelBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
	    ...
	    ...
	    ...
	    
	    if user.check_password(password):

	        if not user.is_active:
	            raise PermissionDenied("Your account requires activation.")
	        return user
	    return None
```

**Comment by tomwojcik** [comment]
You can create a custom exc like `AccountNotActivatedException` and raise it in your `TokenCreateModelBackend`.

Then in the serializer

```
from rest_framework import serializers
from django.contrib.auth import authenticate
from .exceptions import AccountNotActivatedException  # Import your custom exception

class TokenCreateSerializer(serializers.Serializer):
    # Your serializer fields here

    def validate(self, attrs):
        try:
            # Your existing authentication logic here
        except AccountNotActivatedException:
            raise PermissionDenied("Your account requires activation.")
```

Should work.
