### ISSUE TITLE
Docs url() into re_path()

### ISSUE THREAD

**Issue by spinxi** [sunscrapers/djoser#808]
[In docs ](https://djoser.readthedocs.io/en/latest/getting_started.html#configuration) there is mentioned
`url(r'^auth/', include('djoser.urls')),`
isn't that deprecated? would be good if you guys change this into re_path()

**Comment by tomwojcik** [comment]
That's correct. Thank you!

https://github.com/sunscrapers/djoser/pull/806/commits/b65840a7b237694ef7f8ef70cfb1d033c20aefd3
