### ISSUE TITLE
What is the /users/confirm/ endpoint?

### ISSUE THREAD

**Issue by andypal333** [sunscrapers/djoser#814]
In the [docs](https://djoser.readthedocs.io/en/latest/getting_started.html#getting-started) there is an available endpoint `/users/confirm/` but there is no explanation in the docs about this endpoint. What does this endpoint do? What is it used for?

**Comment by haxoza** [comment]
There is no such url and the docs are just wrong. Thanks for finding that!

**Comment by tomwojcik** [comment]
That's correct. Thank you!

https://github.com/sunscrapers/djoser/pull/806/commits/c2b1ffca771df44afe9a42a2efc7fd88b7eac7e9
