### ISSUE TITLE
Djoser password email Typo

### ISSUE THREAD

**Issue by shaikhsufian** [sunscrapers/djoser#815]
I am creating app login authentication system using Django and react, I was able to succesfully implement djoser login auth but when I implement the password/reset/confim, it send a wronf reset link in my email.
Here is my djoser configuration:
DJOSER ={
    'LOGIN_FIELD' : 'username',
    'USER_CREATE_PASSWORD_RETYPE' : True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION' : True,
    'PASSWORD_USERNAME_CHANGED_EMAIL_CONFIRMATION' : True,
    'SEND_CONFIIRMATION_EMAIL' : True,
    'SET_USERNAME_RETYPE' : True,
    'PASSWORD_RESET_CONFIRM_URL' : 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL' : 'username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL' : 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL' : True,
    'SERIALIZERS': {
        'user_create': 'memeapp.serializers.UserCreateSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
        'user': 'memeapp.serializers.UserCreateSerializer',
    }, 
}

URLS.py
    path('auth/',include('djoser.urls')),
    path('auth/',include('djoser.urls.jwt')),
    # path('search/', include('haystack.urls'), name= 'haystack_search'),
]
urlpatterns+=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= [re_path(r'^.*',TemplateView.as_view(template_name="index.html"))] 

and the typo in the reset link
http://http//127.0.0.1:8000//password/reset/confirm/MTg/c5g8bl-44f658078cb0513f30aece38e8e41577

I have no clue why it is preceeding with 2 http and extra backslashes.

**Comment by haxoza** [comment]
Hi there, thanks for using djoser!

Judging from the missing colon `:` between http and slashes it, I guess that the issue is not related directly to djoser but to how you configured your django app or how you construct the url in the template.
