### ISSUE TITLE
PyPi package is missing translations

### ISSUE THREAD

**Issue by oscarfonts** [sunscrapers/djoser#824]
The djoser-2.2.2.tar.gz file from pypi.org is missing the *.mo compiled messages in djoser/locale/*/LC_MESSSAGES.

This causes mail templates to be only partially translated (some of the strings are borrowed from django base translations).

**Comment by tomwojcik** [comment]
I confirm that this was overlooked when moving to poetry and your fix seems to work. Thank you!

**Comment by oscarfonts** [comment]
Unfortunately the most recent version 2.2.3 still doesn't include the .mo files, so translations aren't working.
It seems the release was made just before merging this fix.
Is there any estimate for the next release date?
Thanks @tomwojcik !
