### ISSUE TITLE
email text in multiple languages

### ISSUE THREAD

**Issue by zaubererty** [sunscrapers/djoser#85]
Is there any mechanism to have multiple email text files with different languages?

If not do you have any recommendation on how to implement this, I'm happy to volunteer and create a pull request.

**Comment by mcgeeco** [comment]
I think the best way would be to subcless the view yourself, and override the `get_plain_body_template_name`, `get_html_body_template_name` and `get_subject_template_name` methods to check the current language (with `request.LANGUAGE_CODE` or something like that). Then you could name your templates something like 'registration_french.html', 'registration_english.html' and return the appropriate one.

I could be wrong though!

**Comment by konradhalas** [comment]
Thank you @zaubererty four your question.

As @mcgeeco said, you have to override mentioned methods and create your custom view. Please check https://github.com/sunscrapers/djoser#customization
