### ISSUE TITLE
case sensitive login by email

### ISSUE THREAD

**Issue by saritasa** [sunscrapers/djoser#87]
POST /api/v1/auth/login/
```
{
    "email": "admin@admin.com",
    "password": "admin"
}
```
works fine

but

POST /api/v1/auth/login/
```
{
    "email": "admiN@admin.com",
    "password": "admin"
}
```
produces
```
{
  "non_field_errors": [
    "Unable to login with provided credentials."
  ]
}
```
Let's make login by email case insensitive?

**Comment by apokinsocha** [comment]
you can do that by simply adding a field validation to the djoser registration serializer for the email.

**Comment by rugala** [comment]
@saritasa I don't think that's a good idea - according to [RFC-2821](https://www.ietf.org/rfc/rfc2821.txt): *The local-part of a mailbox MUST BE treated as case sensitive.*

You can always change the default behaviour easily. 

Let's close that issue for now.
