### ISSUE TITLE
400 error when POSTing to /auth/login w/ unique email field

### ISSUE THREAD

**Issue by mvattuone** [sunscrapers/djoser#9]
Hey there, awesome package.  Really makes a lot of sense.

I'm currently tackling an issue, in which I am just trying to access the basic /auth/login endpoint.  

I have a custom user model, which I have created with the help of the django-authtools package.  My username is on an email field, which has unique set to True.

When I try to POST to /login/, I get a 400 error saying that the email field must be unique.  I assume this is because it is trying to POST on a unique field... can that be a PUT, or is there another way to go about solving this issue?

Happy to provide code samples if needed, and I'll keep tinkering around and see if I can come up with a solution.

Thanks again!

**Comment by Djiit** [comment]
Hi, 

Just wanted to say that your commit works perfectly for me with DRF 3.0 / Django 1.7.4

Thx

**Comment by Zeioth** [comment]
Some things are not working in V3, like email confirmation in the registration webservice.

**Comment by konradhalas** [comment]
@Zeioth thank you for reporting, please crete separate issue if there are still problems with email confirmation. Now I'm closing this issue.
