### ISSUE TITLE
possible E-mail improvement

### ISSUE THREAD

**Issue by apokinsocha** [sunscrapers/djoser#91]
I want to quickly say first Djoser is a great package to kickoff DRF REST API projects and I've used it to its absolute maximal intent and beyond. Great job!

I figure I would add my 2cents on some improvements though. Well, actually it's just one, the rest I found very flexible and inline with OOP/DRY.

With respect to sending e-mails, I would look into decoupling it from the DRF Views completely.
Say for example you have attachments (which is not so uncommon), with Djoser as is, I had to make some minor but ugly modifications to Djoser and email views I sub-classed.

Currently Djoser does something similar with Email as TemplateView (or more generally, class based views) in Django, in that there is a "get_context_data" method etc...that is passed in to render the text (the e-mail subject, body etc...) given the path to the template (subject.html, body.html etc...).

This isn't bad, in most cases, but again, if I have to deal with attachments, and also with different types of scenarios (send to multiple recipients, bccs etc...), this may not be the best solution.

Instead of coupling that to the DRF Views, I would decouple it completely and anytime Email functionality is needed, simply reference an Email class within the code and call it.

Here is simple email class I wrote (I called it mixin class by accident) I'm using currently in one of my projects with djoser:

https://github.com/apokinsocha/django-email-mixin/blob/master/django-email-mixin.py

It maybe a bit redundant with respect to djangos existing email function, but I wanted to encapsulate some additional common functionality with respect to e-mails.

Usage example:

``` python
    _file = some_file
    html_body = DjangoEmailWrapper.get_template_text('email_body.txt', context=context)
    subject = DjangoEmailWrapper.get_template_text('subject.txt', context=context, inline=True)
    emails = ['test@gmail.com', 'test2@gmail.com']
    msg = DjangoEmailWrapper(subject, getattr(settings, 'DEFAULT_FROM_EMAIL', None), html_body, bcc=emails, html_body=html_body)
    msg.attach_file(_file)
    msg.send_email()
```

I can do a PR in the near future to integrate it, if there is foreseeable use beyond my own.
A pretty simple change in my view, but I think it cleans things up a bit and also allows to easily call DjangoEmailWrapper in other non-djoser views.

**Comment by mcgeeco** [comment]
I agree with this. I actually had to do something similar as well for doing things like sending activation emails after login attempts for inactive accounts.

**Comment by apokinsocha** [comment]
sounds good. I'll see about a PR within the next few weeks.

**Comment by konradhalas** [comment]
Hi @apokinsocha! First of all thank you alot for your kind words about Djoser and your feedback.

I agree that email functionality should be decoupled somehow from our views, and maybe `SendEmailViewMixin` is not the best idea. Do you have any suggestions how we should connect those two operations (user registration and sending email)? As you said, we shouldn't support only sending emails, but we should provide something more general. Maybe we can use Django signals or implement simple hooks system - definitely this should be something easy to extend for users.

Please give me a few more days, I have to think about it.

**Comment by apokinsocha** [comment]
Hey Konrad,
No problem at all.
I think the main problem here is that the "send_email" (based on the SendEmailViewMixin class on the RegistrationView) function is being called but reference within the view to the djangos email object (in this case EmailMultiAlternatives) is lost, unless it's returned back or modifications are made to the function itself to pass extra kwargs and make some micro-checks (for attachments, bccs or whatever).
These are some of the modifications I had to do initially which I scrapped after more of these kinds of modifications were needed elsewhere. 
ie: 
```msg = self.send_email()
#do something additional with msg, add attachments etc...
msg.send()#not called anymore in the send_email function, but called here in the view```

in this case, it has to be returned from both send_email method from the Mixin class:
    ```def send_email(self, to_email, from_email, context):
        return send_email(to_email, from_email, context, **self.get_send_email_extras())```

as well as in the send_email() function itself.

However the implementation is done, I think the main thing is that the user should simply have either direct or indirect (such as through a class object such as the "DjangoEmailWrapper" I posted above) reference/access to the email object to give full control over the contents of the e-mail message where it's being called within the code block, and that it can be easily overridden/updated via super.

I think a combination of this as well as a Mixin class (not so much different than current) could be apt.
I'm not so sure about the signals though, I think that would decouple it a bit too much.
Just my thoughts...

**Comment by konradhalas** [comment]
@apokinsocha I got the point, but I thinking about something more general.

What would you say about something like that:

```python
# settings.py

DJOSER = {
    'POST_REGISTRATION_HOOK': [
        'djoser.hooks.send_registration_email',
        'yourporject.yourapp.send_sms',
    ]
}

# views.py

class RegistrationView:
   
    def perform_create(self, serializer):
        instance = serializer.save()
        signals.user_registered.send(sender=self.__class__, user=instance, request=self.request)
        for hook in get_post_registration_hooks_from_settings():
            hook(instance)
```

In this case it will be easy to change our default `send_registration_email` with your own.

Is it also a bit too much? Let me know what do you think about my solution.

**Comment by apokinsocha** [comment]
Hey, good job, definitely I think that's a good solution. I looked at multiple use case scenarios and I think it would work in all cases.
To fill in a few more blanks, we'd have this:

```python
from django.utils.module_loading import import_string
from django.conf import settings

DJOSER = {
    'POST_REGISTRATION_HOOKS': [
        'djoser.hooks.send_registration_email',
        'yourporject.yourapp.send_sms',
    ],
   'POST_PASSWORD_RESET_HOOKS': [
    #etc...
   ],
   'POST_SET_USERNAME_HOOKS': [
    #etc..
   ]
}

class RegistrationView:

    def perform_create(self, serializer):
        instance = serializer.save()
        signals.user_registered.send(sender=self.__class__, user=instance, request=self.request)
        for hook in settings['DJOSER'].get(''POST_REGISTRATION_HOOKS'):
            import_string(hook)(instance)
```

Should work, don't see why not.

**Comment by piotr-szpetkowski** [comment]
We've pushed email support to https://github.com/sunscrapers/django-templated-mail/ so I guess that issue can be closed here.
