### ISSUE TITLE
Setting DOMAIN without SITE_NAME will be ignored

### ISSUE THREAD

**Issue by jbrownlucid** [sunscrapers/djoser#92]
Hi, thanks for this handy library.

in [djoser.utils](https://github.com/sunscrapers/djoser/blob/master/djoser/utils.py#L100):
```python
        try:
            domain = django_settings.DJOSER['DOMAIN']
            site_name = django_settings.DJOSER['SITE_NAME']
        except KeyError:
            site = get_current_site(self.request)
            domain, site_name = site.domain, site.name
```

Someone might naively set only the DOMAIN attribute, causing the SendEmailViewMixin to get a KeyError on SITE_NAME and ignore the desired DOMAIN.

**Comment by konradhalas** [comment]
Hi @jbrownlucid! Thank you for pointing out this bug. Fixed in 4ae77be.
