### ISSUE TITLE
Add settings for easily swapping serializers.

### ISSUE THREAD

**Issue by Debetux** [sunscrapers/djoser#93]
Hi,

I wanted to know if it could be a good idea to add new settings for using custom serializers for each endpoint without overriding urls and views. I'm currently using djoser ; and since you removed `LOGIN_AFTER_*` settings, it's difficult to modify the library behaviour. I think theses settings could really be helpful.

What do you think?
If you think it worth the implementation, I'll make a PR in no time. :)

Thanks,
Lancelot.

**Comment by konradhalas** [comment]
Hi @Debetux - thank you once again for your feedback.

Yes, it sounds like a good idea, but TBH I like current solution, it's clean and it does not require any additional mechanism (code). Less code == less bugs, but I understand that it can be a little bit inconvenient when you have to override views and provide custom urls.

So I will say that we can think about it. What other pieces should we configure in this way? This issue somehow related with #91.

@haxoza @rugala - any thoughts?

**Comment by Debetux** [comment]
No problem.
I don't see any other pieces to configure this way right now.

Well, the problematic is that I want to add some custom behaviour without having to add too much complexity in my code (like adding a serializers field) / or for the client. Adding settings relating to serializers seemed to be the simplest solution.
Otherwise, may be there's others way to do this. :)

**Comment by mmarksnippety** [comment]
Settings custom serializers are introduced in #128
