### ISSUE TITLE
get_users in PasswordResetView

### ISSUE THREAD

**Issue by apokinsocha** [sunscrapers/djoser#94]
This is not really an issue but small improvement, I'm not sure what the reasoning is behind using "get_users" (plural) instead of "get_user" (singular)?
This assumes that multiple users can have the same e-mail address.
I'm not sure if that would be a typical use case, I don't think it is.
Another case is if there is a custom User model that uses the e-mail address instead of the username, and the e-mail address must be unique.
I think in both situations, default should be assumed one user can have one e-mail address.
This is in reference to the code for "PasswordResetView":

```python
    def action(self, serializer):
        for user in self.get_users(serializer.data['email']):
            self.send_email(**self.get_send_email_kwargs(user))
        return response.Response(status=status.HTTP_200_OK)

    def get_users(self, email):
        active_users = User._default_manager.filter(
            email__iexact=email,
            is_active=True,
        )
        return (u for u in active_users if u.has_usable_password())
```

a change to just:

```python
    def action(self, serializer):
        users = User.objects.filter(email__iexact=serializer.data['email'], is_active=True)#or get()
        if users.exists():
            user = users.first()
            if user.has_usable_password():
                self.send_email(**self.get_send_email_kwargs(user))
        return response.Response(status=status.HTTP_200_OK)
```

or set "user" on the serializer after validating e-mail and statuses is_active and has_usable_password()

```python
    def action(self, serializer):
        self.send_email(**self.get_send_email_kwargs(serializer.user))
        return response.Response(status=status.HTTP_200_OK)
```

**Comment by konradhalas** [comment]
Hi @apokinsocha, thank you for your question.

This "architecture" is copy-pasted from original `django.contrib.auth.forms.PasswordResetForm`, it looks like this:

```python
class PasswordResetForm(...):

  def get_users(self, email):
      """Given an email, return matching user(s) who should receive a reset.

      This allows subclasses to more easily customize the default policies
      that prevent inactive users and users with unusable passwords from
      resetting their password.
      """
      active_users = get_user_model()._default_manager.filter(
          email__iexact=email, is_active=True)
      return (u for u in active_users if u.has_usable_password())

  def save(self, ...):
      """
      Generates a one-use only link for resetting password and sends to the
      user.
      """
      email = self.cleaned_data["email"]
      for user in self.get_users(email):
          (...)
```

TBH, I also don't know why they are returning generator instead of single user. Does "easily customize" (from docstring) refers to existence of `get_users` method or is it excuse for returning generator? Is it easier to filter collection instead of extend simple if statement? I don't know. But this is what we found in Django and we are trying to handle this in a similar way.

Do you think this is a good reason to leave it as it is or should we simplify it? Let me know.

**Comment by apokinsocha** [comment]
I'm not quite sure either now that you've brought up it was taken from django.
while "get_users" doesn't really make sense for the use cases I've implemented, I guess it doesn't make a difference if more than one user will have the same e-mail address, it will simply send the same e-mail more than once.
