### ISSUE TITLE
The current URL, auth/login/, didn't match any of these.

### ISSUE THREAD

**Issue by tarasinf** [sunscrapers/djoser#96]
Hi, 
When I try to login by command: `curl -X POST http://127.0.0.1:8088/auth/login/ --data 'username=admin&password=admin` then I got html code with error: `The current URL, auth/login/, didn't match any of these.` 
But registration by command `curl -X POST httpername=djoser_3&password=djoser_3'` work great and return: `-data 'use
{"email":"","username":"djoser_3","id":13}`

Do you have any ideas how to fix this?

**Comment by haxoza** [comment]
Hi! Did you follow [instructions for token based authentication](https://github.com/sunscrapers/djoser#token-based-authentication)?

It looks like you didn't use url patterns defined in ['djoser.urls.authtoken'](https://github.com/sunscrapers/djoser/blob/master/djoser/urls/authtoken.py).

```
urlpatterns = patterns('',
    (...),
    url(r'^auth/', include('djoser.urls.authtoken')),
)
```

**Comment by tarasinf** [comment]
@haxoza, What does it mean 'rest_framework' and 'rest_framework.authtoken' in INSTALED_APPS ?

**Comment by konradhalas** [comment]
hi @tarasinf, it means sth like that:

```python
INSTALLED_APPS = (
    'django.contrib.auth',
    (...),
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    (...),
)
```

**Comment by tarasinf** [comment]
Thank, I haven't added: 
`'rest_framework',
'rest_framework.authtoken',`
