### ISSUE TITLE
Registration: Won't allow plus signs in email or username

### ISSUE THREAD

**Issue by cpury** [sunscrapers/djoser#97]
Trying the following:

`curl -X POST http://127.0.0.1:8000/auth/register/ --data 'username=max+djoser@domain.com&password=djoser'`

I get:

`{"username":["Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters."]}`

As you can see, the message even states explicitly that all my special characters are allowed (`+`, `@`, `.`).

But even in emails this seems to be forbidden. I like signing up with `+comment` added to my emails, since this makes testing and debugging easier. This works fine with all Django modules. However, djoser gives me this:

`curl -X POST http://127.0.0.1:8000/auth/register/ --data 'username=max-djoser&password=djoser&email=max+djoser@domain.com'`
`{"email":["Enter a valid email address."]}`

This should definitely work, shouldn't it?

**Comment by cpury** [comment]
Confirmed: Replacing the `+` with `%2B` fixed the problem. Thanks, @mcastle!

**Comment by mcastle** [comment]
No prob!

**Comment by konradhalas** [comment]
Hi guys, happy to see that this is not a bug and thank you for using djoser!
