### ISSUE TITLE
password/reset using email curl issue

### ISSUE THREAD

**Issue by DexterDarkpassenger** [sunscrapers/djoser#98]
curl -X POST http://127.0.0.1:8088/auth/password/reset/  -H 'email:harish@gmail.com' showing 
{"email":["This field is required."]}.
When I passed that curl command, it is showing html page syntax error like

```
       <tr>
          <td>EMAIL_HOST_USER</td>
          <td class="code"><pre>&#39;&#39;</pre></td>
        </tr>
      
    </tbody
  </table>

</div>

  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in your
      Django settings file. Change that to <code>False</code>, and Django will
      display a standard page generated by the handler for this status code.
    </p>
  </div>

</body>
</html>.
```

**Comment by haxoza** [comment]
Hi! I think you use wrong curl parameter `-H` which is for setting HTTP headers and not for sending payload.

The second thing is that you probably didn't set up appropriate Django settings to be able to send email with instructions for password reset. Please check [Django documentation](https://docs.djangoproject.com/en/1.8/topics/email/#smtp-backend). 

I really believe it will help so I'm closing this issue.
